
import { WordClass, Level, Achievement } from './types';

export const INITIAL_LEVELS: Level[] = [
  {
    id: 1,
    title: "Bienvenido a GrammatiCat",
    categoryGroup: 'Tutorial',
    text: "El gato negro corre rápido por el bosque verde.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 60,
    words: [
      { id: "1-1", text: "El", category: WordClass.DETERMINANTE },
      { id: "1-2", text: "gato", category: WordClass.SUSTANTIVO },
      { id: "1-3", text: "negro", category: WordClass.ADJETIVO },
      { id: "1-4", text: "corre", category: WordClass.VERBO },
      { id: "1-5", text: "rápido", category: WordClass.ADVERBIO },
      { id: "1-6", text: "por", category: WordClass.PREPOSICION },
      { id: "1-7", text: "el", category: WordClass.DETERMINANTE },
      { id: "1-8", text: "bosque", category: WordClass.SUSTANTIVO },
      { id: "1-9", text: "verde.", category: WordClass.ADJETIVO },
    ]
  }
];

export const LITERARY_ES_LEVELS: Level[] = [
  { id: 101, title: "La tía Tula - Unamuno", categoryGroup: 'Literatura en español', text: "Rosa se casó primero. Gertrudis, la hermana mayor, parecía resignada a quedarse para vestir imágenes, como decía la gente.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 30, words: [ { id: "101-1", text: "Rosa", category: WordClass.SUSTANTIVO }, { id: "101-2", text: "se", category: WordClass.PRONOMBRE }, { id: "101-3", text: "casó", category: WordClass.VERBO }, { id: "101-4", text: "primero.", category: WordClass.ADVERBIO }, { id: "101-5", text: "Gertrudis,", category: WordClass.SUSTANTIVO }, { id: "101-6", text: "la", category: WordClass.DETERMINANTE }, { id: "101-7", text: "hermana", category: WordClass.SUSTANTIVO }, { id: "101-8", text: "mayor,", category: WordClass.ADJETIVO }, { id: "101-9", text: "parecía", category: WordClass.VERBO }, { id: "101-10", text: "resignada", category: WordClass.ADJETIVO }, { id: "101-11", text: "a", category: WordClass.PREPOSICION }, { id: "101-12", text: "quedarse", category: WordClass.VERBO }, { id: "101-13", text: "para", category: WordClass.PREPOSICION }, { id: "101-14", text: "vestir", category: WordClass.VERBO }, { id: "101-15", text: "imágenes,", category: WordClass.SUSTANTIVO }, { id: "101-16", text: "como", category: WordClass.CONJUNCION }, { id: "101-17", text: "decía", category: WordClass.VERBO }, { id: "101-18", text: "la", category: WordClass.DETERMINANTE }, { id: "101-19", text: "gente.", category: WordClass.SUSTANTIVO } ] },
  { id: 102, title: "El túnel - Sábato", categoryGroup: 'Literatura en español', text: "Bastará decir que soy Juan Pablo Castel, el pintor que mató a María Iribarne. Supongo que el proceso está en el recuerdo de todos.", targetCategory: WordClass.VERBO, timeLimit: 40, words: [ { id: "102-1", text: "Bastará", category: WordClass.VERBO }, { id: "102-2", text: "decir", category: WordClass.VERBO }, { id: "102-3", text: "que", category: WordClass.CONJUNCION }, { id: "102-4", text: "soy", category: WordClass.VERBO }, { id: "102-5", text: "Juan", category: WordClass.SUSTANTIVO }, { id: "102-6", text: "Pablo", category: WordClass.SUSTANTIVO }, { id: "102-7", text: "Castel,", category: WordClass.SUSTANTIVO }, { id: "102-8", text: "el", category: WordClass.DETERMINANTE }, { id: "102-9", text: "pintor", category: WordClass.SUSTANTIVO }, { id: "102-10", text: "que", category: WordClass.PRONOMBRE }, { id: "102-11", text: "mató", category: WordClass.VERBO }, { id: "102-12", text: "a", category: WordClass.PREPOSICION }, { id: "102-13", text: "María", category: WordClass.SUSTANTIVO }, { id: "102-14", text: "Iribarne.", category: WordClass.SUSTANTIVO }, { id: "102-15", text: "Supongo", category: WordClass.VERBO }, { id: "102-16", text: "que", category: WordClass.CONJUNCION }, { id: "102-17", text: "el", category: WordClass.DETERMINANTE }, { id: "102-18", text: "proceso", category: WordClass.SUSTANTIVO }, { id: "102-19", text: "está", category: WordClass.VERBO }, { id: "102-20", text: "en", category: WordClass.PREPOSICION }, { id: "102-21", text: "el", category: WordClass.DETERMINANTE }, { id: "102-22", text: "recuerdo", category: WordClass.SUSTANTIVO }, { id: "102-23", text: "de", category: WordClass.PREPOSICION }, { id: "102-24", text: "todos.", category: WordClass.PRONOMBRE } ] },
  { id: 103, title: "Pedro Páramo - Rulfo", categoryGroup: 'Literatura en español', text: "Vine a Comala porque me dijeron que acá vivía mi padre, un tal Pedro Páramo.", targetCategory: WordClass.PRONOMBRE, timeLimit: 35, words: [ { id: "103-1", text: "Vine", category: WordClass.VERBO }, { id: "103-2", text: "a", category: WordClass.PREPOSICION }, { id: "103-3", text: "Comala", category: WordClass.SUSTANTIVO }, { id: "103-4", text: "porque", category: WordClass.CONJUNCION }, { id: "103-5", text: "me", category: WordClass.PRONOMBRE }, { id: "103-6", text: "dijeron", category: WordClass.VERBO }, { id: "103-7", text: "que", category: WordClass.CONJUNCION }, { id: "103-8", text: "acá", category: WordClass.ADVERBIO }, { id: "103-9", text: "vivía", category: WordClass.VERBO }, { id: "103-10", text: "mi", category: WordClass.DETERMINANTE }, { id: "103-11", text: "padre,", category: WordClass.SUSTANTIVO }, { id: "103-12", text: "un", category: WordClass.DETERMINANTE }, { id: "103-13", text: "tal", category: WordClass.DETERMINANTE }, { id: "103-14", text: "Pedro", category: WordClass.SUSTANTIVO }, { id: "103-15", text: "Páramo.", category: WordClass.SUSTANTIVO } ] },
  { id: 104, title: "Martín Fierro - Hernández", categoryGroup: 'Literatura en español', text: "Aquí me pongo a cantar al compás de la vigüela.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 35, words: [ { id: "104-1", text: "Aquí", category: WordClass.ADVERBIO }, { id: "104-2", text: "me", category: WordClass.PRONOMBRE }, { id: "104-3", text: "pongo", category: WordClass.VERBO }, { id: "104-4", text: "a", category: WordClass.PREPOSICION }, { id: "104-5", text: "cantar", category: WordClass.VERBO }, { id: "104-6", text: "al", category: WordClass.PREPOSICION }, { id: "104-7", text: "compás", category: WordClass.SUSTANTIVO }, { id: "104-8", text: "de", category: WordClass.PREPOSICION }, { id: "104-9", text: "la", category: WordClass.DETERMINANTE }, { id: "104-10", text: "vigüela.", category: WordClass.SUSTANTIVO } ] },
  { id: 105, title: "Doña Bárbara - Gallegos", categoryGroup: 'Literatura en español', text: "Un bongo remonta el Arauca bordeando las barrancas derecha.", targetCategory: WordClass.ADJETIVO, timeLimit: 35, words: [ { id: "105-1", text: "Un", category: WordClass.DETERMINANTE }, { id: "105-2", text: "bongo", category: WordClass.SUSTANTIVO }, { id: "105-3", text: "remonta", category: WordClass.VERBO }, { id: "105-4", text: "el", category: WordClass.DETERMINANTE }, { id: "105-5", text: "Arauca", category: WordClass.SUSTANTIVO }, { id: "105-6", text: "bordeando", category: WordClass.VERBO }, { id: "105-7", text: "las", category: WordClass.DETERMINANTE }, { id: "105-8", text: "barrancas", category: WordClass.SUSTANTIVO }, { id: "105-9", text: "derecha.", category: WordClass.ADJETIVO } ] },
  { id: 106, title: "La vorágine - Rivera", categoryGroup: 'Literatura en español', text: "Jugué mi corazón al azar y me lo ganó la Violencia.", targetCategory: WordClass.PREPOSICION, timeLimit: 35, words: [ { id: "106-9", text: "Jugué", category: WordClass.VERBO }, { id: "106-10", text: "mi", category: WordClass.DETERMINANTE }, { id: "106-11", text: "corazón", category: WordClass.SUSTANTIVO }, { id: "106-12", text: "al", category: WordClass.PREPOSICION }, { id: "106-13", text: "azar", category: WordClass.SUSTANTIVO }, { id: "106-14", text: "y", category: WordClass.CONJUNCION }, { id: "106-15", text: "me", category: WordClass.PRONOMBRE }, { id: "106-16", text: "lo", category: WordClass.PRONOMBRE }, { id: "106-17", text: "ganó", category: WordClass.VERBO }, { id: "106-18", text: "la", category: WordClass.DETERMINANTE }, { id: "106-19", text: "Violencia.", category: WordClass.SUSTANTIVO } ] },
  { id: 107, title: "Los de abajo - Azuela", categoryGroup: 'Literatura en español', text: "Demetrio Macías regreaba como general victorioso.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 30, words: [ { id: "107-1", text: "Demetrio", category: WordClass.SUSTANTIVO }, { id: "107-2", text: "Macías", category: WordClass.SUSTANTIVO }, { id: "107-13", text: "regresaba", category: WordClass.VERBO }, { id: "107-14", text: "como", category: WordClass.CONJUNCION }, { id: "107-15", text: "general", category: WordClass.SUSTANTIVO }, { id: "107-16", text: "victorioso.", category: WordClass.ADJETIVO } ] },
  { id: 108, title: "El reino de este mundo - Carpentier", categoryGroup: 'Literatura en español', text: "Ti Noel observaba cómo las llamas lamían las vigas del techo.", targetCategory: WordClass.VERBO, timeLimit: 35, words: [ { id: "108-1", text: "Ti", category: WordClass.SUSTANTIVO }, { id: "108-2", text: "Noel", category: WordClass.SUSTANTIVO }, { id: "108-3", text: "observaba", category: WordClass.VERBO }, { id: "108-4", text: "cómo", category: WordClass.ADVERBIO }, { id: "108-5", text: "las", category: WordClass.DETERMINANTE }, { id: "108-6", text: "llamas", category: WordClass.SUSTANTIVO }, { id: "108-7", text: "lamían", category: WordClass.VERBO }, { id: "108-8", text: "las", category: WordClass.DETERMINANTE }, { id: "108-9", text: "vigas", category: WordClass.SUSTANTIVO }, { id: "108-10", text: "del", category: WordClass.PREPOSICION }, { id: "108-11", text: "techo.", category: WordClass.SUSTANTIVO } ] },
  { id: 109, title: "La casa verde - Vargas Llosa", categoryGroup: 'Literatura en español', text: "El sargento mira la oscura corriente del río.", targetCategory: WordClass.ADJETIVO, timeLimit: 30, words: [ { id: "109-1", text: "El", category: WordClass.DETERMINANTE }, { id: "109-2", text: "sargento", category: WordClass.SUSTANTIVO }, { id: "109-3", text: "mira", category: WordClass.VERBO }, { id: "109-4", text: "la", category: WordClass.DETERMINANTE }, { id: "109-5", text: "oscura", category: WordClass.ADJETIVO }, { id: "109-6", text: "corriente", category: WordClass.SUSTANTIVO }, { id: "109-7", text: "del", category: WordClass.PREPOSICION }, { id: "109-8", text: "río.", category: WordClass.SUSTANTIVO } ] },
  { id: 110, title: "Rayuela - Cortázar", categoryGroup: 'Literatura en español', text: "Andábamos sin buscarnos pero sabiendo que andábamos.", targetCategory: WordClass.PRONOMBRE, timeLimit: 30, words: [ { id: "110-1", text: "Andábamos", category: WordClass.VERBO }, { id: "110-2", text: "sin", category: WordClass.PREPOSICION }, { id: "110-3", text: "buscarnos", category: WordClass.VERBO }, { id: "110-4", text: "pero", category: WordClass.CONJUNCION }, { id: "110-5", text: "sabiendo", category: WordClass.VERBO }, { id: "110-6", text: "que", category: WordClass.CONJUNCION }, { id: "110-7", text: "andábamos.", category: WordClass.VERBO } ] },
  { id: 111, title: "El Señor Presidente - Asturias", categoryGroup: 'Literatura en español', text: "Nadie sabía de dónde venía aquel sonido metálico.", targetCategory: WordClass.ADVERBIO, timeLimit: 30, words: [ { id: "111-8", text: "Nadie", category: WordClass.PRONOMBRE }, { id: "111-9", text: "sabía", category: WordClass.VERBO }, { id: "111-10", text: "de", category: WordClass.PREPOSICION }, { id: "111-11", text: "dónde", category: WordClass.ADVERBIO }, { id: "111-12", text: "venía", category: WordClass.VERBO }, { id: "111-13", text: "aquel", category: WordClass.DETERMINANTE }, { id: "111-14", text: "sonido", category: WordClass.SUSTANTIVO }, { id: "111-15", text: "metálico.", category: WordClass.ADJETIVO } ] },
  { id: 112, title: "Los pasos perdidos - Carpentier", categoryGroup: 'Literatura en español', text: "Hacía cuatro años que no había vuelto.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 35, words: [ { id: "112-1", text: "Hacía", category: WordClass.VERBO }, { id: "112-2", text: "cuatro", category: WordClass.DETERMINANTE }, { id: "112-3", text: "años", category: WordClass.SUSTANTIVO }, { id: "112-7", text: "que", category: WordClass.CONJUNCION }, { id: "112-8", text: "no", category: WordClass.ADVERBIO }, { id: "112-9", text: "había", category: WordClass.VERBO }, { id: "112-10", text: "vuelto.", category: WordClass.VERBO } ] },
  { id: 113, title: "Sobre héroes y tumbas - Sábato", categoryGroup: 'Literatura en español', text: "Cuando volvió en sí se encontró rodeado de rostros ansiosos.", targetCategory: WordClass.PREPOSICION, timeLimit: 35, words: [ { id: "113-1", text: "Cuando", category: WordClass.CONJUNCION }, { id: "113-2", text: "volvió", category: WordClass.VERBO }, { id: "113-3", text: "en", category: WordClass.PREPOSICION }, { id: "113-4", text: "sí", category: WordClass.PRONOMBRE }, { id: "113-5", text: "se", category: WordClass.PRONOMBRE }, { id: "113-6", text: "encontró", category: WordClass.VERBO }, { id: "113-7", text: "rodeado", category: WordClass.ADJETIVO }, { id: "113-8", text: "de", category: WordClass.PREPOSICION }, { id: "113-9", text: "rostros", category: WordClass.SUSTANTIVO }, { id: "113-10", text: "ansiosos.", category: WordClass.ADJETIVO } ] },
  { id: 114, title: "Huasipungo - Icaza", categoryGroup: 'Literatura en español', text: "Los indios trabajaban desde el amanecer hasta el anochecer.", targetCategory: WordClass.VERBO, timeLimit: 40, words: [ { id: "114-1", text: "Los", category: WordClass.DETERMINANTE }, { id: "114-2", text: "indios", category: WordClass.SUSTANTIVO }, { id: "114-3", text: "trabajaban", category: WordClass.VERBO }, { id: "114-4", text: "desde", category: WordClass.PREPOSICION }, { id: "114-5", text: "el", category: WordClass.DETERMINANTE }, { id: "114-6", text: "amanecer", category: WordClass.SUSTANTIVO }, { id: "114-7", text: "hasta", category: WordClass.PREPOSICION }, { id: "114-8", text: "el", category: WordClass.DETERMINANTE }, { id: "114-9", text: "anochecer.", category: WordClass.SUSTANTIVO } ] },
  { id: 115, title: "Nada - Laforet", categoryGroup: 'Literatura en español', text: "Llegué a Barcelona a medianoche.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 35, words: [ { id: "115-10", text: "Llegué", category: WordClass.VERBO }, { id: "115-11", text: "a", category: WordClass.PREPOSICION }, { id: "115-12", text: "Barcelona", category: WordClass.SUSTANTIVO }, { id: "115-13", text: "a", category: WordClass.PREPOSICION }, { id: "115-14", text: "medianoche.", category: WordClass.SUSTANTIVO } ] },
  { id: 116, title: "El Aleph - Borges", categoryGroup: 'Literatura en español', text: "La candente mañana de febrero en que Beatriz Viterbo murió.", targetCategory: WordClass.ADJETIVO, timeLimit: 40, words: [ { id: "116-1", text: "La", category: WordClass.DETERMINANTE }, { id: "116-2", text: "candente", category: WordClass.ADJETIVO }, { id: "116-3", text: "mañana", category: WordClass.SUSTANTIVO }, { id: "116-4", text: "de", category: WordClass.PREPOSICION }, { id: "116-5", text: "febrero", category: WordClass.SUSTANTIVO }, { id: "116-6", text: "en", category: WordClass.PREPOSICION }, { id: "116-7", text: "que", category: WordClass.CONJUNCION }, { id: "116-8", text: "Beatriz", category: WordClass.SUSTANTIVO }, { id: "116-9", text: "Viterbo", category: WordClass.SUSTANTIVO }, { id: "116-10", text: "murió.", category: WordClass.VERBO } ] },
  { id: 117, title: "Santa - Gamboa", categoryGroup: 'Literatura en español', text: "Santa nació en el pueblecito de Chimalistac.", targetCategory: WordClass.PREPOSICION, timeLimit: 35, words: [ { id: "117-1", text: "Santa", category: WordClass.SUSTANTIVO }, { id: "117-2", text: "nació", category: WordClass.VERBO }, { id: "117-3", text: "en", category: WordClass.PREPOSICION }, { id: "117-4", text: "el", category: WordClass.DETERMINANTE }, { id: "117-5", text: "pueblecito", category: WordClass.SUSTANTIVO }, { id: "117-6", text: "de", category: WordClass.PREPOSICION }, { id: "117-7", text: "Chimalistac.", category: WordClass.SUSTANTIVO } ] },
  { id: 118, title: "Conversación en La Catedral", categoryGroup: 'Literatura en español', text: "Santiago mira la avenida Tacna sin amor.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 40, words: [ { id: "118-7", text: "Santiago", category: WordClass.SUSTANTIVO }, { id: "118-8", text: "mira", category: WordClass.VERBO }, { id: "118-9", text: "la", category: WordClass.DETERMINANTE }, { id: "118-10", text: "avenida", category: WordClass.SUSTANTIVO }, { id: "118-11", text: "Tacna", category: WordClass.SUSTANTIVO }, { id: "118-12", text: "sin", category: WordClass.PREPOSICION }, { id: "118-13", text: "amor.", category: WordClass.SUSTANTIVO } ] },
  { id: 119, title: "Fervor de Buenos Aires - Borges", categoryGroup: 'Literatura en español', text: "Las calles de Buenos Aires ya son mi entraña.", targetCategory: WordClass.VERBO, timeLimit: 40, words: [ { id: "119-1", text: "Las", category: WordClass.DETERMINANTE }, { id: "119-2", text: "calles", category: WordClass.SUSTANTIVO }, { id: "119-3", text: "de", category: WordClass.PREPOSICION }, { id: "119-4", text: "Buenos", category: WordClass.SUSTANTIVO }, { id: "119-5", text: "Aires", category: WordClass.SUSTANTIVO }, { id: "119-6", text: "ya", category: WordClass.ADVERBIO }, { id: "119-7", text: "son", category: WordClass.VERBO }, { id: "119-8", text: "mi", category: WordClass.DETERMINANTE }, { id: "119-9", text: "entraña.", category: WordClass.SUSTANTIVO } ] },
  { id: 120, title: "El llano en llamas - Rulfo", categoryGroup: 'Literatura en español', text: "Nos habían dado la tierra.", targetCategory: WordClass.CONJUNCION, timeLimit: 35, words: [ { id: "120-1", text: "Nos", category: WordClass.PRONOMBRE }, { id: "120-2", text: "habían", category: WordClass.VERBO }, { id: "120-3", text: "dado", category: WordClass.VERBO }, { id: "120-4", text: "la", category: WordClass.DETERMINANTE }, { id: "120-5", text: "tierra.", category: WordClass.SUSTANTIVO } ] },
  { id: 121, title: "Canaima - Gallegos", categoryGroup: 'Literatura en español', text: "Marcos Vargas llegó al caney.", targetCategory: WordClass.ADVERBIO, timeLimit: 35, words: [ { id: "121-1", text: "Marcos", category: WordClass.SUSTANTIVO }, { id: "121-2", text: "Vargas", category: WordClass.SUSTANTIVO }, { id: "121-3", text: "llegó", category: WordClass.VERBO }, { id: "121-4", text: "al", category: WordClass.PREPOSICION }, { id: "121-5", text: "caney.", category: WordClass.SUSTANTIVO } ] },
  { id: 122, title: "El mundo es ancho y ajeno - Alegría", categoryGroup: 'Literatura en español', text: "La comunidad de Rumi tiene tierras inmemoriales.", targetCategory: WordClass.DETERMINANTE, timeLimit: 40, words: [ { id: "122-1", text: "La", category: WordClass.DETERMINANTE }, { id: "122-2", text: "comunidad", category: WordClass.SUSTANTIVO }, { id: "122-3", text: "de", category: WordClass.PREPOSICION }, { id: "122-4", text: "Rumi", category: WordClass.SUSTANTIVO }, { id: "122-5", text: "tiene", category: WordClass.VERBO }, { id: "122-6", text: "tierras", category: WordClass.SUSTANTIVO }, { id: "122-10", text: "inmemoriales.", category: WordClass.ADJETIVO } ] },
  { id: 123, title: "Los ríos profundos - Arguedas", categoryGroup: 'Literatura en español', text: "Infundía respeto seriamente.", targetCategory: WordClass.PRONOMBRE, timeLimit: 35, words: [ { id: "123-1", text: "Infundía", category: WordClass.VERBO }, { id: "123-2", text: "respeto", category: WordClass.SUSTANTIVO }, { id: "123-18", text: "seriamente.", category: WordClass.ADVERBIO } ] },
  { id: 124, title: "La colmena - Cela", categoryGroup: 'Literatura en español', text: "Doña Rosa va y viene por el café.", targetCategory: WordClass.ADJETIVO, timeLimit: 35, words: [ { id: "124-1", text: "Doña", category: WordClass.SUSTANTIVO }, { id: "124-2", text: "Rosa", category: WordClass.SUSTANTIVO }, { id: "124-3", text: "va", category: WordClass.VERBO }, { id: "124-4", text: "y", category: WordClass.CONJUNCION }, { id: "124-5", text: "viene", category: WordClass.VERBO }, { id: "124-6", text: "por", category: WordClass.PREPOSICION }, { id: "124-11", text: "el", category: WordClass.DETERMINANTE }, { id: "124-11-2", text: "café.", category: WordClass.SUSTANTIVO } ] },
  { id: 125, title: "Don Quijote - Cervantes", categoryGroup: 'Literatura en español', text: "En un lugar de la Mancha de cuyo nombre no quiero acordarme.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 25, words: [ { id: "125-1", text: "En", category: WordClass.PREPOSICION }, { id: "125-2", text: "un", category: WordClass.DETERMINANTE }, { id: "125-3", text: "lugar", category: WordClass.SUSTANTIVO }, { id: "125-4", text: "de", category: WordClass.PREPOSICION }, { id: "125-5", text: "la", category: WordClass.DETERMINANTE }, { id: "125-6", text: "Mancha", category: WordClass.SUSTANTIVO }, { id: "125-7", text: "de", category: WordClass.PREPOSICION }, { id: "125-8", text: "cuyo", category: WordClass.DETERMINANTE }, { id: "125-9", text: "nombre", category: WordClass.SUSTANTIVO }, { id: "125-10", text: "no", category: WordClass.ADVERBIO }, { id: "125-11", text: "quiero", category: WordClass.VERBO }, { id: "125-12", text: "acordarme.", category: WordClass.VERBO } ] },
  { id: 126, title: "Tiempo de silencio - Martín-Santos", categoryGroup: 'Literatura en español', text: "Había una vez un rey que tenía tres hijas.", targetCategory: WordClass.VERBO, timeLimit: 40, words: [ { id: "126-1", text: "Había", category: WordClass.VERBO }, { id: "126-2", text: "una", category: WordClass.DETERMINANTE }, { id: "126-3", text: "vez", category: WordClass.SUSTANTIVO }, { id: "126-4", text: "un", category: WordClass.DETERMINANTE }, { id: "126-5", text: "rey", category: WordClass.SUSTANTIVO }, { id: "126-6", text: "que", category: WordClass.PRONOMBRE }, { id: "126-7", text: "tenía", category: WordClass.VERBO }, { id: "126-8", text: "tres", category: WordClass.DETERMINANTE }, { id: "126-9", text: "hijas.", category: WordClass.SUSTANTIVO } ] },
  { id: 127, title: "Campos de Castilla - Machado", categoryGroup: 'Literatura en español', text: "He andado muchos caminos he abierto muchas veredas.", targetCategory: WordClass.VERBO, timeLimit: 30, words: [ { id: "127-1", text: "He", category: WordClass.VERBO }, { id: "127-2", text: "andado", category: WordClass.VERBO }, { id: "127-3", text: "muchos", category: WordClass.DETERMINANTE }, { id: "127-4", text: "caminos", category: WordClass.SUSTANTIVO }, { id: "127-5", text: "he", category: WordClass.VERBO }, { id: "127-6", text: "abierto", category: WordClass.VERBO }, { id: "127-7", text: "muchas", category: WordClass.DETERMINANTE }, { id: "127-8", text: "veredas.", category: WordClass.SUSTANTIVO } ] }
];

export const LITERARY_UNIVERSAL_LEVELS: Level[] = [
  { id: 201, title: "El Principito - Saint-Exupéry", categoryGroup: 'Literatura universal', text: "Todas las personas mayores fueron primero niños aunque pocas de ellas lo recuerden.", targetCategory: WordClass.ADJETIVO, timeLimit: 30, words: [ { id: "201-1", text: "Todas", category: WordClass.DETERMINANTE }, { id: "201-2", text: "las", category: WordClass.DETERMINANTE }, { id: "201-3", text: "personas", category: WordClass.SUSTANTIVO }, { id: "201-4", text: "mayores", category: WordClass.ADJETIVO }, { id: "201-5", text: "fueron", category: WordClass.VERBO }, { id: "201-6", text: "primero", category: WordClass.ADVERBIO }, { id: "201-7", text: "niños,", category: WordClass.SUSTANTIVO }, { id: "201-8", text: "aunque", category: WordClass.CONJUNCION }, { id: "201-9", text: "pocas", category: WordClass.DETERMINANTE }, { id: "201-10", text: "de", category: WordClass.PREPOSICION }, { id: "201-11", text: "ellas", category: WordClass.PRONOMBRE }, { id: "201-12", text: "lo", category: WordClass.PRONOMBRE }, { id: "201-13", text: "recuerden.", category: WordClass.VERBO } ] },
  { id: 202, title: "1984 - George Orwell", categoryGroup: 'Literatura universal', text: "Era un día luminoso y frío de abril y los relojes daban las trece.", targetCategory: WordClass.ADJETIVO, timeLimit: 25, words: [ { id: "202-1", text: "Era", category: WordClass.VERBO }, { id: "202-2", text: "un", category: WordClass.DETERMINANTE }, { id: "202-3", text: "día", category: WordClass.SUSTANTIVO }, { id: "202-4", text: "luminoso", category: WordClass.ADJETIVO }, { id: "202-5", text: "y", category: WordClass.CONJUNCION }, { id: "202-6", text: "frío", category: WordClass.ADJETIVO }, { id: "202-7", text: "de", category: WordClass.PREPOSICION }, { id: "202-8", text: "abril,", category: WordClass.SUSTANTIVO }, { id: "202-9", text: "y", category: WordClass.CONJUNCION }, { id: "202-10", text: "los", category: WordClass.DETERMINANTE }, { id: "202-11", text: "relojes", category: WordClass.SUSTANTIVO }, { id: "202-12", text: "daban", category: WordClass.VERBO }, { id: "202-13", text: "las", category: WordClass.DETERMINANTE }, { id: "202-14", text: "trece.", category: WordClass.DETERMINANTE } ] },
  { id: 203, title: "Hamlet - Shakespeare", categoryGroup: 'Literatura universal', text: "Ser o no ser esa es la cuestión.", targetCategory: WordClass.VERBO, timeLimit: 20, words: [ { id: "203-1", text: "Ser", category: WordClass.VERBO }, { id: "203-2", text: "o", category: WordClass.CONJUNCION }, { id: "203-3", text: "no", category: WordClass.ADVERBIO }, { id: "203-4", text: "ser,", category: WordClass.VERBO }, { id: "203-5", text: "esa", category: WordClass.PRONOMBRE }, { id: "203-6", text: "es", category: WordClass.VERBO }, { id: "203-7", text: "la", category: WordClass.DETERMINANTE }, { id: "203-8", text: "cuestión.", category: WordClass.SUSTANTIVO } ] },
  { id: 204, title: "Otra vuelta de tuerca - Henry James", categoryGroup: 'Literatura universal', text: "La historia nos había mantenido sin aliento.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 45, words: [ { id: "204-1", text: "La", category: WordClass.DETERMINANTE }, { id: "204-2", text: "historia", category: WordClass.SUSTANTIVO }, { id: "204-3", text: "nos", category: WordClass.PRONOMBRE }, { id: "204-4", text: "había", category: WordClass.VERBO }, { id: "204-5", text: "mantenido", category: WordClass.VERBO }, { id: "204-10", text: "sin", category: WordClass.PREPOSICION }, { id: "204-11", text: "aliento.", category: WordClass.SUSTANTIVO } ] },
  { id: 205, title: "Orgullo y prejuicio - Jane Austen", categoryGroup: 'Literatura universal', text: "Es una verdad universalmente reconocida.", targetCategory: WordClass.ADJETIVO, timeLimit: 40, words: [ { id: "205-1", text: "Es", category: WordClass.VERBO }, { id: "205-2", text: "una", category: WordClass.DETERMINANTE }, { id: "205-3", text: "verdad", category: WordClass.SUSTANTIVO }, { id: "205-4", text: "universalmente", category: WordClass.ADVERBIO }, { id: "205-5", text: "reconocida.", category: WordClass.ADJETIVO } ] },
  { id: 206, title: "Moby Dick - Herman Melville", categoryGroup: 'Literatura universal', text: "Llamadme Ismael.", targetCategory: WordClass.VERBO, timeLimit: 15, words: [ { id: "206-1", text: "Llamadme", category: WordClass.VERBO }, { id: "206-2", text: "Ismael.", category: WordClass.SUSTANTIVO } ] },
  { id: 207, title: "La metamorfosis - Franz Kafka", categoryGroup: 'Literatura universal', text: "Una mañana Gregorio Samsa se despertó.", targetCategory: WordClass.ADJETIVO, timeLimit: 35, words: [ { id: "207-1", text: "Una", category: WordClass.DETERMINANTE }, { id: "207-2", text: "mañana", category: WordClass.SUSTANTIVO }, { id: "207-7", text: "Gregorio", category: WordClass.SUSTANTIVO }, { id: "207-8", text: "Samsa", category: WordClass.SUSTANTIVO }, { id: "207-9", text: "se", category: WordClass.PRONOMBRE }, { id: "207-10", text: "despertó.", category: WordClass.VERBO } ] },
  { id: 208, title: "En busca del tiempo perdido - Proust", categoryGroup: 'Literatura universal', text: "Durante mucho tiempo me acosté temprano.", targetCategory: WordClass.ADVERBIO, timeLimit: 20, words: [ { id: "208-1", text: "Durante", category: WordClass.PREPOSICION }, { id: "208-2", text: "mucho", category: WordClass.DETERMINANTE }, { id: "208-3", text: "tiempo", category: WordClass.SUSTANTIVO }, { id: "208-4", text: "me", category: WordClass.PRONOMBRE }, { id: "208-5", text: "acosté", category: WordClass.VERBO }, { id: "208-6", text: "temprano.", category: WordClass.ADVERBIO } ] },
  { id: 209, title: "El gran Gatsby - Fitzgerald", categoryGroup: 'Literatura universal', text: "En mis años mi padre me dio un consejo.", targetCategory: WordClass.PRONOMBRE, timeLimit: 30, words: [ { id: "209-1", text: "En", category: WordClass.PREPOSICION }, { id: "209-2", text: "mis", category: WordClass.DETERMINANTE }, { id: "209-3", text: "años", category: WordClass.SUSTANTIVO }, { id: "209-6", text: "mi", category: WordClass.DETERMINANTE }, { id: "209-7", text: "padre", category: WordClass.SUSTANTIVO }, { id: "209-8", text: "me", category: WordClass.PRONOMBRE }, { id: "209-9", text: "dio", category: WordClass.VERBO }, { id: "209-10", text: "un", category: WordClass.DETERMINANTE }, { id: "209-11", text: "consejo.", category: WordClass.SUSTANTIVO } ] },
  { id: 210, title: "Crimen y castigo - Dostoievski", categoryGroup: 'Literatura universal', text: "A principios hacía un calor extraordinario.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 35, words: [ { id: "210-1", text: "A", category: WordClass.PREPOSICION }, { id: "210-2", text: "principios", category: WordClass.SUSTANTIVO }, { id: "210-5", text: "hacía", category: WordClass.VERBO }, { id: "210-6", text: "un", category: WordClass.DETERMINANTE }, { id: "210-7", text: "calor", category: WordClass.SUSTANTIVO }, { id: "210-8", text: "extraordinario.", category: WordClass.ADJETIVO } ] },
  { id: 211, title: "El extranjero - Albert Camus", categoryGroup: 'Literatura universal', text: "Hoy ha muerto mamá.", targetCategory: WordClass.VERBO, timeLimit: 25, words: [ { id: "211-1", text: "Hoy", category: WordClass.ADVERBIO }, { id: "211-2", text: "ha", category: WordClass.VERBO }, { id: "211-3", text: "muerto", category: WordClass.VERBO }, { id: "211-4", text: "mamá.", category: WordClass.SUSTANTIVO } ] },
  { id: 212, title: "Ana Karenina - Lev Tolstói", categoryGroup: 'Literatura universal', text: "Todas las familias felices se parecen.", targetCategory: WordClass.ADJETIVO, timeLimit: 40, words: [ { id: "212-1", text: "Todas", category: WordClass.DETERMINANTE }, { id: "212-2", text: "las", category: WordClass.DETERMINANTE }, { id: "212-3", text: "familias", category: WordClass.SUSTANTIVO }, { id: "212-4", text: "felices", category: WordClass.ADJETIVO }, { id: "212-5", text: "se", category: WordClass.PRONOMBRE }, { id: "212-6", text: "parecen.", category: WordClass.VERBO } ] },
  { id: 213, title: "Ulises - James Joyce", categoryGroup: 'Literatura universal', text: "Mulligan apareció en lo alto de la escalera.", targetCategory: WordClass.ADJETIVO, timeLimit: 30, words: [ { id: "213-5", text: "Mulligan", category: WordClass.SUSTANTIVO }, { id: "213-6", text: "apareció", category: WordClass.VERBO }, { id: "213-7", text: "en", category: WordClass.PREPOSICION }, { id: "213-8", text: "lo", category: WordClass.DETERMINANTE }, { id: "213-9", text: "alto", category: WordClass.ADJETIVO }, { id: "213-10", text: "de", category: WordClass.PREPOSICION }, { id: "213-11", text: "la", category: WordClass.DETERMINANTE }, { id: "213-12", text: "escalera.", category: WordClass.SUSTANTIVO } ] },
  { id: 214, title: "La Odisea - Homero", categoryGroup: 'Literatura universal', text: "Cuéntame musa la historia del hombre.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 25, words: [ { id: "214-1", text: "Cuéntame", category: WordClass.VERBO }, { id: "214-2", text: "musa", category: WordClass.SUSTANTIVO }, { id: "214-3", text: "la", category: WordClass.DETERMINANTE }, { id: "214-4", text: "historia", category: WordClass.SUSTANTIVO }, { id: "214-5", text: "del", category: WordClass.PREPOSICION }, { id: "214-6", text: "hombre.", category: WordClass.SUSTANTIVO } ] },
  { id: 215, title: "Lolita - Vladimir Nabokov", categoryGroup: 'Literatura universal', text: "Lolita luz de mi vida.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 20, words: [ { id: "215-1", text: "Lolita", category: WordClass.SUSTANTIVO }, { id: "215-2", text: "luz", category: WordClass.SUSTANTIVO }, { id: "215-3", text: "de", category: WordClass.PREPOSICION }, { id: "215-4", text: "mi", category: WordClass.DETERMINANTE }, { id: "215-5", text: "vida.", category: WordClass.SUSTANTIVO } ] },
  { id: 216, title: "Madame Bovary - Flaubert", categoryGroup: 'Literatura universal', text: "Estábamos en clase cuando entró el director.", targetCategory: WordClass.VERBO, timeLimit: 35, words: [ { id: "216-1", text: "Estábamos", category: WordClass.VERBO }, { id: "216-2", text: "en", category: WordClass.PREPOSICION }, { id: "216-3", text: "clase", category: WordClass.SUSTANTIVO }, { id: "216-4", text: "cuando", category: WordClass.CONJUNCION }, { id: "216-5", text: "entró", category: WordClass.VERBO }, { id: "216-6", text: "el", category: WordClass.DETERMINANTE }, { id: "216-7", text: "director.", category: WordClass.SUSTANTIVO } ] },
  { id: 217, title: "El guardián entre el centeno", categoryGroup: 'Literatura universal', text: "Lo primero es dónde nací.", targetCategory: WordClass.PRONOMBRE, timeLimit: 40, words: [ { id: "217-11", text: "Lo", category: WordClass.DETERMINANTE }, { id: "217-12", text: "primero", category: WordClass.ADJETIVO }, { id: "217-16", text: "es", category: WordClass.VERBO }, { id: "217-17", text: "dónde", category: WordClass.ADVERBIO }, { id: "217-18", text: "nací.", category: WordClass.VERBO } ] },
  { id: 218, title: "Los miserables - Victor Hugo", categoryGroup: 'Literatura universal', text: "Libros como este no serán inútiles.", targetCategory: WordClass.CONJUNCION, timeLimit: 35, words: [ { id: "218-9", text: "Libros", category: WordClass.SUSTANTIVO }, { id: "218-10", text: "como", category: WordClass.CONJUNCION }, { id: "218-11", text: "este", category: WordClass.DETERMINANTE }, { id: "218-12", text: "no", category: WordClass.ADVERBIO }, { id: "218-13", text: "serán", category: WordClass.VERBO }, { id: "218-14", text: "inútiles.", category: WordClass.ADJETIVO } ] },
  { id: 219, title: "Fahrenheit 451 - Bradbury", categoryGroup: 'Literatura universal', text: "Era un placer quemar.", targetCategory: WordClass.VERBO, timeLimit: 15, words: [ { id: "219-1", text: "Era", category: WordClass.VERBO }, { id: "219-2", text: "un", category: WordClass.DETERMINANTE }, { id: "219-3", text: "placer", category: WordClass.SUSTANTIVO }, { id: "219-4", text: "quemar.", category: WordClass.VERBO } ] },
  { id: 220, title: "Jane Eyre - Brontë", categoryGroup: 'Literatura universal', text: "Aquel día fue imposible dar un paseo.", targetCategory: WordClass.DETERMINANTE, timeLimit: 20, words: [ { id: "220-1", text: "Aquel", category: WordClass.DETERMINANTE }, { id: "220-2", text: "día", category: WordClass.SUSTANTIVO }, { id: "220-3", text: "fue", category: WordClass.VERBO }, { id: "220-4", text: "imposible", category: WordClass.ADJETIVO }, { id: "220-5", text: "dar", category: WordClass.VERBO }, { id: "220-6", text: "un", category: WordClass.DETERMINANTE }, { id: "220-7", text: "paseo.", category: WordClass.SUSTANTIVO } ] },
  { id: 221, title: "El señor de los anillos", categoryGroup: 'Literatura universal', text: "Bilbo Bolsón anunció su cumpleaños.", targetCategory: WordClass.SUSTANTIVO, timeLimit: 45, words: [ { id: "221-4", text: "Bilbo", category: WordClass.SUSTANTIVO }, { id: "221-5", text: "Bolsón", category: WordClass.SUSTANTIVO }, { id: "221-9", text: "anunció", category: WordClass.VERBO }, { id: "221-13", text: "su", category: WordClass.DETERMINANTE }, { id: "221-14", text: "cumpleaños.", category: WordClass.SUSTANTIVO } ] },
  { id: 222, title: "Rayuela - Cortázar", categoryGroup: 'Literatura universal', text: "Encontraría a la Maga.", targetCategory: WordClass.VERBO, timeLimit: 30, words: [ { id: "222-1", text: "Encontraría", category: WordClass.VERBO }, { id: "222-2", text: "a", category: WordClass.PREPOSICION }, { id: "222-3", text: "la", category: WordClass.DETERMINANTE }, { id: "222-4", text: "Maga.", category: WordClass.SUSTANTIVO } ] },
  { id: 223, title: "Don Quijote - Miguel de Cervantes", categoryGroup: 'Literatura universal', text: "Vivía un hidalgo en un lugar.", targetCategory: WordClass.VERBO, timeLimit: 35, words: [ { id: "223-13", text: "Vivía", category: WordClass.VERBO }, { id: "223-14", text: "un", category: WordClass.DETERMINANTE }, { id: "223-15", text: "hidalgo", category: WordClass.SUSTANTIVO }, { id: "223-1", text: "en", category: WordClass.PREPOSICION }, { id: "223-2", text: "un", category: WordClass.DETERMINANTE }, { id: "223-3", text: "lugar.", category: WordClass.SUSTANTIVO } ] },
  { id: 224, title: "La divina comedia - Dante", categoryGroup: 'Literatura universal', text: "Selva oscura de la vida.", targetCategory: WordClass.ADJETIVO, timeLimit: 30, words: [ { id: "224-12", text: "Selva", category: WordClass.SUSTANTIVO }, { id: "224-13", text: "oscura", category: WordClass.ADJETIVO }, { id: "224-5", text: "de", category: WordClass.PREPOSICION }, { id: "224-6", text: "la", category: WordClass.DETERMINANTE }, { id: "224-7", text: "vida.", category: WordClass.SUSTANTIVO } ] },
  { id: 225, title: "El retrato de Dorian Gray", categoryGroup: 'Literatura universal', text: "Estudio lleno del rico aroma.", targetCategory: WordClass.ADJETIVO, timeLimit: 50, words: [ { id: "225-2", text: "Estudio", category: WordClass.SUSTANTIVO }, { id: "225-4", text: "lleno", category: WordClass.ADJETIVO }, { id: "225-5", text: "del", category: WordClass.PREPOSICION }, { id: "225-6", text: "rico", category: WordClass.ADJETIVO }, { id: "225-7", text: "aroma.", category: WordClass.SUSTANTIVO } ] },
  { id: 226, title: "Beloved - Toni Morrison", categoryGroup: 'Literatura universal', text: "Malicioso lleno de rencor.", targetCategory: WordClass.ADJETIVO, timeLimit: 25, words: [ { id: "226-5", text: "Malicioso", category: WordClass.ADJETIVO }, { id: "226-6", text: "lleno", category: WordClass.ADJETIVO }, { id: "226-7", text: "de", category: WordClass.PREPOSICION }, { id: "226-8", text: "rencor.", category: WordClass.SUSTANTIVO } ] }
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  { id: 'tutorial_hero', title: 'Un buen comienzo', description: 'Completa el tutorial y aprende las bases.', icon: 'fa-graduation-cap', unlocked: false },
  { id: 'first_steps', title: '¡Primeros pasos!', description: 'Supera con éxito 5 textos (excluyendo tutorial).', icon: 'fa-shoe-prints', unlocked: false, progress: 0, goal: 5 },
  { id: 'half_world', title: 'Medio mundo', description: 'Supera el 50% de los textos en español y universal.', icon: 'fa-map-marked-alt', unlocked: false },
  { id: 'max_knowledge', title: 'Conocimiento máximo', description: 'Supera el 100% de los textos en una de las categorías literarias.', icon: 'fa-award', unlocked: false },
  { id: 'absolute_knowledge', title: 'Conocimiento absoluto', description: 'Supera el 100% de los textos de ambas categorías literarias.', icon: 'fa-crown', unlocked: false },
  
  { id: 'challenge_10', title: 'Por el buen camino', description: 'Supera 10 textos en el modo reto.', icon: 'fa-route', unlocked: false, progress: 0, goal: 10 },
  { id: 'challenge_25', title: 'El camino del ascenso', description: 'Supera 25 textos en el modo reto.', icon: 'fa-mountain', unlocked: false, progress: 0, goal: 25 },
  { id: 'challenge_35', title: 'Viendo de cerca la cima', description: 'Supera 35 textos en el modo reto.', icon: 'fa-telescope', unlocked: false, progress: 0, goal: 35 },
  { id: 'challenge_50', title: 'Más allá del saber', description: 'Supera 50 textos en el modo reto.', icon: 'fa-infinity', unlocked: false, progress: 0, goal: 50 },
  
  { id: 'all_categories_single', title: '¡A por todas!', description: 'Completa todas las categorías de palabras en un mismo texto.', icon: 'fa-object-group', unlocked: false },
  { id: 'all_categories_all_texts', title: 'No se puede saber más', description: 'Supera todos los textos predefinidos respondiendo a todas sus categorías.', icon: 'fa-brain', unlocked: false },
  
  { id: 'perfectionist', title: 'Perfeccionista', description: 'Termina un nivel sin cometer ni un solo error.', icon: 'fa-star', unlocked: false },
  { id: 'architect', title: 'Arquitecto Literario', description: 'Crea y guarda tu propio nivel en el editor.', icon: 'fa-tools', unlocked: false },
  { id: 'unstoppable', title: 'Imparable', description: 'Consigue acumular el máximo de 5 vidas.', icon: 'fa-heartbeat', unlocked: false }
];

export const KONAMI_CODE = ['ArrowUp', 'ArrowUp', 'ArrowDown', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowLeft', 'ArrowRight', 'b', 'a'];
