
import { WordClass, Level, Achievement } from './types';

export const INITIAL_LEVELS: Level[] = [
  {
    id: 1,
    title: "El Bosque Mágico",
    categoryGroup: 'Entrenamiento',
    text: "El gato negro corre rápido por el bosque verde y saltó sobre una rama pequeña.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 30,
    words: [
      { id: "1-1", text: "El", category: WordClass.DETERMINANTE },
      { id: "1-2", text: "gato", category: WordClass.SUSTANTIVO },
      { id: "1-3", text: "negro", category: WordClass.ADJETIVO },
      { id: "1-4", text: "corre", category: WordClass.VERBO },
      { id: "1-5", text: "rápido", category: WordClass.ADVERBIO },
      { id: "1-6", text: "por", category: WordClass.PREPOSICION },
      { id: "1-7", text: "el", category: WordClass.DETERMINANTE },
      { id: "1-8", text: "bosque", category: WordClass.SUSTANTIVO },
      { id: "1-9", text: "verde", category: WordClass.ADJETIVO },
      { id: "1-10", text: "y", category: WordClass.CONJUNCION },
      { id: "1-11", text: "saltó", category: WordClass.VERBO },
      { id: "1-12", text: "sobre", category: WordClass.PREPOSICION },
      { id: "1-13", text: "una", category: WordClass.DETERMINANTE },
      { id: "1-14", text: "rama", category: WordClass.SUSTANTIVO },
      { id: "1-15", text: "pequeña.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 2,
    title: "La Aventura Espacial",
    categoryGroup: 'Entrenamiento',
    text: "Los astronautas valientes exploran planetas lejanos con sus naves plateadas.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 25,
    words: [
      { id: "2-1", text: "Los", category: WordClass.DETERMINANTE },
      { id: "2-2", text: "astronautas", category: WordClass.SUSTANTIVO },
      { id: "2-3", text: "valientes", category: WordClass.ADJETIVO },
      { id: "2-4", text: "exploran", category: WordClass.VERBO },
      { id: "2-5", text: "planetas", category: WordClass.SUSTANTIVO },
      { id: "2-6", text: "lejanos", category: WordClass.ADJETIVO },
      { id: "2-7", text: "con", category: WordClass.PREPOSICION },
      { id: "2-8", text: "sus", category: WordClass.DETERMINANTE },
      { id: "2-9", text: "naves", category: WordClass.SUSTANTIVO },
      { id: "2-10", text: "plateadas.", category: WordClass.ADJETIVO },
    ]
  }
];

export const LITERARY_ES_LEVELS: Level[] = [
  {
    id: 101,
    title: "La tía Tula - Unamuno",
    text: "Rosa se casó primero. Gertrudis, la hermana mayor, parecía resignada a quedarse para vestir imágenes, como decía la gente.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 30,
    words: [
      { id: "1-1", text: "Rosa", category: WordClass.SUSTANTIVO },
      { id: "1-2", text: "se", category: WordClass.PRONOMBRE },
      { id: "1-3", text: "casó", category: WordClass.VERBO },
      { id: "1-4", text: "primero", category: WordClass.ADVERBIO },
      { id: "1-5", text: "Gertrudis", category: WordClass.SUSTANTIVO },
      { id: "1-6", text: "la", category: WordClass.DETERMINANTE },
      { id: "1-7", text: "hermana", category: WordClass.SUSTANTIVO },
      { id: "1-8", text: "mayor", category: WordClass.ADJETIVO },
      { id: "1-9", text: "parecía", category: WordClass.VERBO },
      { id: "1-10", text: "resignada", category: WordClass.ADJETIVO },
      { id: "1-11", text: "a", category: WordClass.PREPOSICION },
      { id: "1-12", text: "quedarse", category: WordClass.VERBO },
      { id: "1-13", text: "para", category: WordClass.PREPOSICION },
      { id: "1-14", text: "vestir", category: WordClass.VERBO },
      { id: "1-15", text: "imágenes", category: WordClass.SUSTANTIVO },
      { id: "1-16", text: "como", category: WordClass.CONJUNCION },
      { id: "1-17", text: "decía", category: WordClass.VERBO },
      { id: "1-18", text: "la", category: WordClass.DETERMINANTE },
      { id: "1-19", text: "gente", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 102,
    title: "El túnel - Sábato (Argentina)",
    text: "Bastará decir que soy Juan Pablo Castel, el pintor que mató a María Iribarne. Supongo que el proceso está en el recuerdo de todos.",
    targetCategory: WordClass.VERBO,
    timeLimit: 40,
    words: [
      { id: "2-1", text: "Bastará", category: WordClass.VERBO },
      { id: "2-2", text: "decir", category: WordClass.VERBO },
      { id: "2-3", text: "que", category: WordClass.CONJUNCION },
      { id: "2-4", text: "soy", category: WordClass.VERBO },
      { id: "2-5", text: "Juan", category: WordClass.SUSTANTIVO },
      { id: "2-6", text: "Pablo", category: WordClass.SUSTANTIVO },
      { id: "2-7", text: "Castel", category: WordClass.SUSTANTIVO },
      { id: "2-8", text: "el", category: WordClass.DETERMINANTE },
      { id: "2-9", text: "pintor", category: WordClass.SUSTANTIVO },
      { id: "2-10", text: "que", category: WordClass.PRONOMBRE },
      { id: "2-11", text: "mató", category: WordClass.VERBO },
      { id: "2-12", text: "a", category: WordClass.PREPOSICION },
      { id: "2-13", text: "María", category: WordClass.SUSTANTIVO },
      { id: "2-14", text: "Iribarne", category: WordClass.SUSTANTIVO },
      { id: "2-15", text: "Supongo", category: WordClass.VERBO },
      { id: "2-16", text: "que", category: WordClass.CONJUNCION },
      { id: "2-17", text: "el", category: WordClass.DETERMINANTE },
      { id: "2-18", text: "proceso", category: WordClass.SUSTANTIVO },
      { id: "2-19", text: "está", category: WordClass.VERBO },
      { id: "2-20", text: "en", category: WordClass.PREPOSICION },
      { id: "2-21", text: "el", category: WordClass.DETERMINANTE },
      { id: "2-22", text: "recuerdo", category: WordClass.SUSTANTIVO },
      { id: "2-23", text: "de", category: WordClass.PREPOSICION },
      { id: "2-24", text: "todos", category: WordClass.PRONOMBRE },
    ]
  },
  {
    id: 103,
    title: "Pedro Páramo - Rulfo (México)",
    text: "Vine a Comala porque me dijeron que acá vivía mi padre, un tal Pedro Páramo. Mi madre me lo dijo.",
    targetCategory: WordClass.PRONOMBRE,
    timeLimit: 35,
    words: [
      { id: "3-1", text: "Vine", category: WordClass.VERBO },
      { id: "3-2", text: "a", category: WordClass.PREPOSICION },
      { id: "3-3", text: "Comala", category: WordClass.SUSTANTIVO },
      { id: "3-4", text: "porque", category: WordClass.CONJUNCION },
      { id: "3-5", text: "me", category: WordClass.PRONOMBRE },
      { id: "3-6", text: "dijeron", category: WordClass.VERBO },
      { id: "3-7", text: "que", category: WordClass.CONJUNCION },
      { id: "3-8", text: "acá", category: WordClass.ADVERBIO },
      { id: "3-9", text: "vivía", category: WordClass.VERBO },
      { id: "3-10", text: "mi", category: WordClass.DETERMINANTE },
      { id: "3-11", text: "padre", category: WordClass.SUSTANTIVO },
      { id: "3-12", text: "un", category: WordClass.DETERMINANTE },
      { id: "3-13", text: "tal", category: WordClass.DETERMINANTE },
      { id: "3-14", text: "Pedro", category: WordClass.SUSTANTIVO },
      { id: "3-15", text: "Páramo", category: WordClass.SUSTANTIVO },
      { id: "3-16", text: "Mi", category: WordClass.DETERMINANTE },
      { id: "3-17", text: "madre", category: WordClass.SUSTANTIVO },
      { id: "3-18", text: "me", category: WordClass.PRONOMBRE },
      { id: "3-19", text: "lo", category: WordClass.PRONOMBRE },
      { id: "3-20", text: "dijo", category: WordClass.VERBO },
    ]
  },
  {
    id: 104,
    title: "Martín Fierro - Hernández (Argentina)",
    text: "Aquí me pongo a cantar al compás de la vigüela, que el hombre que lo desvela una pena extraordinaria.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 35,
    words: [
      { id: "4-1", text: "Aquí", category: WordClass.ADVERBIO },
      { id: "4-2", text: "me", category: WordClass.PRONOMBRE },
      { id: "4-3", text: "pongo", category: WordClass.VERBO },
      { id: "4-4", text: "a", category: WordClass.PREPOSICION },
      { id: "4-5", text: "cantar", category: WordClass.VERBO },
      { id: "4-6", text: "al", category: WordClass.PREPOSICION },
      { id: "4-7", text: "compás", category: WordClass.SUSTANTIVO },
      { id: "4-8", text: "de", category: WordClass.PREPOSICION },
      { id: "4-9", text: "la", category: WordClass.DETERMINANTE },
      { id: "4-10", text: "vigüela", category: WordClass.SUSTANTIVO },
      { id: "4-11", text: "que", category: WordClass.CONJUNCION },
      { id: "4-12", text: "el", category: WordClass.DETERMINANTE },
      { id: "4-13", text: "hombre", category: WordClass.SUSTANTIVO },
      { id: "4-14", text: "que", category: WordClass.PRONOMBRE },
      { id: "4-15", text: "lo", category: WordClass.PRONOMBRE },
      { id: "4-16", text: "desvela", category: WordClass.VERBO },
      { id: "4-17", text: "una", category: WordClass.DETERMINANTE },
      { id: "4-18", text: "pena", category: WordClass.SUSTANTIVO },
      { id: "4-19", text: "extraordinaria", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 105,
    title: "Doña Bárbara - Gallegos (Venezuela)",
    text: "Un bongo remonta el Arauca bordeando las barrancas de la margen derecha. La tripulación está formada por cuatro hombres.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 35,
    words: [
      { id: "105-1", text: "Un", category: WordClass.DETERMINANTE },
      { id: "105-2", text: "bongo", category: WordClass.SUSTANTIVO },
      { id: "105-3", text: "remonta", category: WordClass.VERBO },
      { id: "105-4", text: "el", category: WordClass.DETERMINANTE },
      { id: "105-5", text: "Arauca", category: WordClass.SUSTANTIVO },
      { id: "105-6", text: "bordeando", category: WordClass.VERBO },
      { id: "105-7", text: "las", category: WordClass.DETERMINANTE },
      { id: "105-8", text: "barrancas", category: WordClass.SUSTANTIVO },
      { id: "105-9", text: "de", category: WordClass.PREPOSICION },
      { id: "105-10", text: "la", category: WordClass.DETERMINANTE },
      { id: "105-11", text: "margen", category: WordClass.SUSTANTIVO },
      { id: "105-12", text: "derecha", category: WordClass.ADJETIVO },
      { id: "105-13", text: "La", category: WordClass.DETERMINANTE },
      { id: "105-14", text: "tripulación", category: WordClass.SUSTANTIVO },
      { id: "105-15", text: "está", category: WordClass.VERBO },
      { id: "105-16", text: "formada", category: WordClass.ADJETIVO },
      { id: "105-17", text: "por", category: WordClass.PREPOSICION },
      { id: "105-18", text: "cuatro", category: WordClass.DETERMINANTE },
      { id: "105-19", text: "hombres", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 106,
    title: "La vorágine - Rivera (Colombia)",
    text: "Antes que me hubiera apasionado por mujer alguna, jugué mi corazón al azar y me lo ganó la Violencia.",
    targetCategory: WordClass.PREPOSICION,
    timeLimit: 35,
    words: [
      { id: "106-1", text: "Antes", category: WordClass.ADVERBIO },
      { id: "106-2", text: "que", category: WordClass.CONJUNCION },
      { id: "106-3", text: "me", category: WordClass.PRONOMBRE },
      { id: "106-4", text: "hubiera", category: WordClass.VERBO },
      { id: "106-5", text: "apasionado", category: WordClass.VERBO },
      { id: "106-6", text: "por", category: WordClass.PREPOSICION },
      { id: "106-7", text: "mujer", category: WordClass.SUSTANTIVO },
      { id: "106-8", text: "alguna", category: WordClass.DETERMINANTE },
      { id: "106-9", text: "jugué", category: WordClass.VERBO },
      { id: "106-10", text: "mi", category: WordClass.DETERMINANTE },
      { id: "106-11", text: "corazón", category: WordClass.SUSTANTIVO },
      { id: "106-12", text: "al", category: WordClass.PREPOSICION },
      { id: "106-13", text: "azar", category: WordClass.SUSTANTIVO },
      { id: "106-14", text: "y", category: WordClass.CONJUNCION },
      { id: "106-15", text: "me", category: WordClass.PRONOMBRE },
      { id: "106-16", text: "lo", category: WordClass.PRONOMBRE },
      { id: "106-17", text: "ganó", category: WordClass.VERBO },
      { id: "106-18", text: "la", category: WordClass.DETERMINANTE },
      { id: "106-19", text: "Violencia", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 107,
    title: "Los de abajo - Azuela (México)",
    text: "A Demetrio Macías, la revolución lo había sacado de su rancho. Ahora regresaba como general victorioso.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 30,
    words: [
      { id: "107-1", text: "A", category: WordClass.PREPOSICION },
      { id: "107-2", text: "Demetrio", category: WordClass.SUSTANTIVO },
      { id: "107-3", text: "Macías", category: WordClass.SUSTANTIVO },
      { id: "107-4", text: "la", category: WordClass.DETERMINANTE },
      { id: "107-5", text: "revolución", category: WordClass.SUSTANTIVO },
      { id: "107-6", text: "lo", category: WordClass.PRONOMBRE },
      { id: "107-7", text: "había", category: WordClass.VERBO },
      { id: "107-8", text: "sacado", category: WordClass.VERBO },
      { id: "107-9", text: "de", category: WordClass.PREPOSICION },
      { id: "107-10", text: "su", category: WordClass.DETERMINANTE },
      { id: "107-11", text: "rancho", category: WordClass.SUSTANTIVO },
      { id: "107-12", text: "Ahora", category: WordClass.ADVERBIO },
      { id: "107-13", text: "regresaba", category: WordClass.VERBO },
      { id: "107-14", text: "como", category: WordClass.CONJUNCION },
      { id: "107-15", text: "general", category: WordClass.SUSTANTIVO },
      { id: "107-16", text: "victorioso", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 108,
    title: "El reino de este mundo - Carpentier (Cuba)",
    text: "Ti Noel observaba cómo las llamas lamían las vigas del techo. El incendio había comenzado en la cocina principal.",
    targetCategory: WordClass.VERBO,
    timeLimit: 35,
    words: [
      { id: "108-1", text: "Ti", category: WordClass.SUSTANTIVO },
      { id: "108-2", text: "Noel", category: WordClass.SUSTANTIVO },
      { id: "108-3", text: "observaba", category: WordClass.VERBO },
      { id: "108-4", text: "cómo", category: WordClass.ADVERBIO },
      { id: "108-5", text: "las", category: WordClass.DETERMINANTE },
      { id: "108-6", text: "llamas", category: WordClass.SUSTANTIVO },
      { id: "108-7", text: "lamían", category: WordClass.VERBO },
      { id: "108-8", text: "las", category: WordClass.DETERMINANTE },
      { id: "108-9", text: "vigas", category: WordClass.SUSTANTIVO },
      { id: "108-10", text: "del", category: WordClass.PREPOSICION },
      { id: "108-11", text: "techo", category: WordClass.SUSTANTIVO },
      { id: "108-12", text: "El", category: WordClass.DETERMINANTE },
      { id: "108-13", text: "incendio", category: WordClass.SUSTANTIVO },
      { id: "108-14", text: "había", category: WordClass.VERBO },
      { id: "108-15", text: "comenzado", category: WordClass.VERBO },
      { id: "108-16", text: "en", category: WordClass.PREPOSICION },
      { id: "108-17", text: "la", category: WordClass.DETERMINANTE },
      { id: "108-18", text: "cocina", category: WordClass.SUSTANTIVO },
      { id: "108-19", text: "principal", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 109,
    title: "La casa verde - Vargas Llosa (Perú)",
    text: "El sargento mira la oscura corriente del río. Los guardias están tendidos bajo el poncho, durmiendo.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 30,
    words: [
      { id: "109-1", text: "El", category: WordClass.DETERMINANTE },
      { id: "109-2", text: "sargento", category: WordClass.SUSTANTIVO },
      { id: "109-3", text: "mira", category: WordClass.VERBO },
      { id: "109-4", text: "la", category: WordClass.DETERMINANTE },
      { id: "109-5", text: "oscura", category: WordClass.ADJETIVO },
      { id: "109-6", text: "corriente", category: WordClass.SUSTANTIVO },
      { id: "109-7", text: "del", category: WordClass.PREPOSICION },
      { id: "109-8", text: "río", category: WordClass.SUSTANTIVO },
      { id: "109-9", text: "Los", category: WordClass.DETERMINANTE },
      { id: "109-10", text: "guardias", category: WordClass.SUSTANTIVO },
      { id: "109-11", text: "están", category: WordClass.VERBO },
      { id: "109-12", text: "tendidos", category: WordClass.ADJETIVO },
      { id: "109-13", text: "bajo", category: WordClass.PREPOSICION },
      { id: "109-14", text: "el", category: WordClass.DETERMINANTE },
      { id: "109-15", text: "poncho", category: WordClass.SUSTANTIVO },
      { id: "109-16", text: "durmiendo", category: WordClass.VERBO },
    ]
  },
  {
    id: 110,
    title: "Rayuela - Cortázar (Argentina)",
    text: "Andábamos sin buscarnos pero sabiendo que andábamos para encontrarnos. Maga reía de mis explicaciones.",
    targetCategory: WordClass.PRONOMBRE,
    timeLimit: 30,
    words: [
      { id: "110-1", text: "Andábamos", category: WordClass.VERBO },
      { id: "110-2", text: "sin", category: WordClass.PREPOSICION },
      { id: "110-3", text: "buscarnos", category: WordClass.VERBO },
      { id: "110-4", text: "pero", category: WordClass.CONJUNCION },
      { id: "110-5", text: "sabiendo", category: WordClass.VERBO },
      { id: "110-6", text: "que", category: WordClass.CONJUNCION },
      { id: "110-7", text: "andábamos", category: WordClass.VERBO },
      { id: "110-8", text: "para", category: WordClass.PREPOSICION },
      { id: "110-9", text: "encontrarnos", category: WordClass.VERBO },
      { id: "110-10", text: "Maga", category: WordClass.SUSTANTIVO },
      { id: "110-11", text: "reía", category: WordClass.VERBO },
      { id: "110-12", text: "de", category: WordClass.PREPOSICION },
      { id: "110-13", text: "mis", category: WordClass.DETERMINANTE },
      { id: "110-14", text: "explicaciones", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 111,
    title: "El Señor Presidente - Asturias (Guatemala)",
    text: "En ese instante se oyeron las campanadas. Nadie sabía de dónde venía aquel sonido metálico y persistente.",
    targetCategory: WordClass.ADVERBIO,
    timeLimit: 30,
    words: [
      { id: "111-1", text: "En", category: WordClass.PREPOSICION },
      { id: "111-2", text: "ese", category: WordClass.DETERMINANTE },
      { id: "111-3", text: "instante", category: WordClass.SUSTANTIVO },
      { id: "111-4", text: "se", category: WordClass.PRONOMBRE },
      { id: "111-5", text: "oyeron", category: WordClass.VERBO },
      { id: "111-6", text: "las", category: WordClass.DETERMINANTE },
      { id: "111-7", text: "campanadas", category: WordClass.SUSTANTIVO },
      { id: "111-8", text: "Nadie", category: WordClass.PRONOMBRE },
      { id: "111-9", text: "sabía", category: WordClass.VERBO },
      { id: "111-10", text: "de", category: WordClass.PREPOSICION },
      { id: "111-11", text: "dónde", category: WordClass.ADVERBIO },
      { id: "111-12", text: "venía", category: WordClass.VERBO },
      { id: "111-13", text: "aquel", category: WordClass.DETERMINANTE },
      { id: "111-14", text: "sonido", category: WordClass.SUSTANTIVO },
      { id: "111-15", text: "metálico", category: WordClass.ADJETIVO },
      { id: "111-16", text: "y", category: WordClass.CONJUNCION },
      { id: "111-17", text: "persistente", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 112,
    title: "Los pasos perdidos - Carpentier (Cuba)",
    text: "Hacía cuatro años y siete meses que no había vuelto a la ciudad donde transcurrió mi adolescencia.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 35,
    words: [
      { id: "112-1", text: "Hacía", category: WordClass.VERBO },
      { id: "112-2", text: "cuatro", category: WordClass.DETERMINANTE },
      { id: "112-3", text: "años", category: WordClass.SUSTANTIVO },
      { id: "112-4", text: "y", category: WordClass.CONJUNCION },
      { id: "112-5", text: "siete", category: WordClass.DETERMINANTE },
      { id: "112-6", text: "meses", category: WordClass.SUSTANTIVO },
      { id: "112-7", text: "que", category: WordClass.CONJUNCION },
      { id: "112-8", text: "no", category: WordClass.ADVERBIO },
      { id: "112-9", text: "había", category: WordClass.VERBO },
      { id: "112-10", text: "vuelto", category: WordClass.VERBO },
      { id: "112-11", text: "a", category: WordClass.PREPOSICION },
      { id: "112-12", text: "la", category: WordClass.DETERMINANTE },
      { id: "112-13", text: "ciudad", category: WordClass.SUSTANTIVO },
      { id: "112-14", text: "donde", category: WordClass.ADVERBIO },
      { id: "112-15", text: "transcurrió", category: WordClass.VERBO },
      { id: "112-16", text: "mi", category: WordClass.DETERMINANTE },
      { id: "112-17", text: "adolescencia", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 113,
    title: "Sobre héroes y tumbas - Sábato (Argentina)",
    text: "Cuando volvió en sí se encontró rodeado de rostros ansiosos. Alguien le ofrecía un vaso de agua fría.",
    targetCategory: WordClass.PREPOSICION,
    timeLimit: 35,
    words: [
      { id: "113-1", text: "Cuando", category: WordClass.CONJUNCION },
      { id: "113-2", text: "volvió", category: WordClass.VERBO },
      { id: "113-3", text: "en", category: WordClass.PREPOSICION },
      { id: "113-4", text: "sí", category: WordClass.PRONOMBRE },
      { id: "113-5", text: "se", category: WordClass.PRONOMBRE },
      { id: "113-6", text: "encontró", category: WordClass.VERBO },
      { id: "113-7", text: "rodeado", category: WordClass.ADJETIVO },
      { id: "113-8", text: "de", category: WordClass.PREPOSICION },
      { id: "113-9", text: "rostros", category: WordClass.SUSTANTIVO },
      { id: "113-10", text: "ansiosos", category: WordClass.ADJETIVO },
      { id: "113-11", text: "Alguien", category: WordClass.PRONOMBRE },
      { id: "113-12", text: "le", category: WordClass.PRONOMBRE },
      { id: "113-13", text: "ofrecía", category: WordClass.VERBO },
      { id: "113-14", text: "un", category: WordClass.DETERMINANTE },
      { id: "113-15", text: "vaso", category: WordClass.SUSTANTIVO },
      { id: "113-16", text: "de", category: WordClass.PREPOSICION },
      { id: "113-17", text: "agua", category: WordClass.SUSTANTIVO },
      { id: "113-18", text: "fría", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 114,
    title: "Huasipungo - Icaza (Ecuador)",
    text: "Los indios trabajaban desde el amanecer hasta el anochecer. Sus manos callosas sangraban entre las piedras ásperas del camino.",
    targetCategory: WordClass.VERBO,
    timeLimit: 40,
    words: [
      { id: "114-1", text: "Los", category: WordClass.DETERMINANTE },
      { id: "114-2", text: "indios", category: WordClass.SUSTANTIVO },
      { id: "114-3", text: "trabajaban", category: WordClass.VERBO },
      { id: "114-4", text: "desde", category: WordClass.PREPOSICION },
      { id: "114-5", text: "el", category: WordClass.DETERMINANTE },
      { id: "114-6", text: "amanecer", category: WordClass.SUSTANTIVO },
      { id: "114-7", text: "hasta", category: WordClass.PREPOSICION },
      { id: "114-8", text: "el", category: WordClass.DETERMINANTE },
      { id: "114-9", text: "anochecer", category: WordClass.SUSTANTIVO },
      { id: "114-10", text: "Sus", category: WordClass.DETERMINANTE },
      { id: "114-11", text: "manos", category: WordClass.SUSTANTIVO },
      { id: "114-12", text: "callosas", category: WordClass.ADJETIVO },
      { id: "114-13", text: "sangraban", category: WordClass.VERBO },
      { id: "114-14", text: "entre", category: WordClass.PREPOSICION },
      { id: "114-15", text: "las", category: WordClass.DETERMINANTE },
      { id: "114-16", text: "piedras", category: WordClass.SUSTANTIVO },
      { id: "114-17", text: "ásperas", category: WordClass.ADJETIVO },
      { id: "114-18", text: "del", category: WordClass.PREPOSICION },
      { id: "114-19", text: "camino", category: WordClass.SUSTANTIVO },
    ]
  },
   {
    id: 115,
    title: "Nada - Laforet (España)",
    text: "Por dificultades en el último momento para adquirir billetes, llegué a Barcelona a medianoche.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 35,
    words: [
      { id: "115-1", text: "Por", category: WordClass.PREPOSICION },
      { id: "115-2", text: "dificultades", category: WordClass.SUSTANTIVO },
      { id: "115-3", text: "en", category: WordClass.PREPOSICION },
      { id: "115-4", text: "el", category: WordClass.DETERMINANTE },
      { id: "115-5", text: "último", category: WordClass.ADJETIVO },
      { id: "115-6", text: "momento", category: WordClass.SUSTANTIVO },
      { id: "115-7", text: "para", category: WordClass.PREPOSICION },
      { id: "115-8", text: "adquirir", category: WordClass.VERBO },
      { id: "115-9", text: "billetes", category: WordClass.SUSTANTIVO },
      { id: "115-10", text: "llegué", category: WordClass.VERBO },
      { id: "115-11", text: "a", category: WordClass.PREPOSICION },
      { id: "115-12", text: "Barcelona", category: WordClass.SUSTANTIVO },
      { id: "115-13", text: "a", category: WordClass.PREPOSICION },
      { id: "115-14", text: "medianoche", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 116,
    title: "El Aleph - Borges (Argentina)",
    text: "La candente mañana de febrero en que Beatriz Viterbo murió, después de una imperiosa agonia que no se rebajó un solo instante.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 40,
    words: [
      { id: "116-1", text: "La", category: WordClass.DETERMINANTE },
      { id: "116-2", text: "candente", category: WordClass.ADJETIVO },
      { id: "116-3", text: "mañana", category: WordClass.SUSTANTIVO },
      { id: "116-4", text: "de", category: WordClass.PREPOSICION },
      { id: "116-5", text: "febrero", category: WordClass.SUSTANTIVO },
      { id: "116-6", text: "en", category: WordClass.PREPOSICION },
      { id: "116-7", text: "que", category: WordClass.CONJUNCION },
      { id: "116-8", text: "Beatriz", category: WordClass.SUSTANTIVO },
      { id: "116-9", text: "Viterbo", category: WordClass.SUSTANTIVO },
      { id: "116-10", text: "murió", category: WordClass.VERBO },
      { id: "116-11", text: "después", category: WordClass.ADVERBIO },
      { id: "116-12", text: "de", category: WordClass.PREPOSICION },
      { id: "116-13", text: "una", category: WordClass.DETERMINANTE },
      { id: "116-14", text: "imperiosa", category: WordClass.ADJETIVO },
      { id: "116-15", text: "agonía", category: WordClass.SUSTANTIVO },
      { id: "116-16", text: "que", category: WordClass.PRONOMBRE },
      { id: "116-17", text: "no", category: WordClass.ADVERBIO },
      { id: "116-18", text: "se", category: WordClass.PRONOMBRE },
      { id: "116-19", text: "rebajó", category: WordClass.VERBO },
      { id: "116-20", text: "un", category: WordClass.DETERMINANTE },
      { id: "116-21", text: "solo", category: WordClass.ADJETIVO },
      { id: "116-22", text: "instante", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 117,
    title: "Santa - Gamboa (México)",
    text: "Santa nació en el pueblecito de Chimalistac, allá por los rumbos de San Ángel. Era hija de labradores honrados.",
    targetCategory: WordClass.PREPOSICION,
    timeLimit: 35,
    words: [
      { id: "117-1", text: "Santa", category: WordClass.SUSTANTIVO },
      { id: "117-2", text: "nació", category: WordClass.VERBO },
      { id: "117-3", text: "en", category: WordClass.PREPOSICION },
      { id: "117-4", text: "el", category: WordClass.DETERMINANTE },
      { id: "117-5", text: "pueblecito", category: WordClass.SUSTANTIVO },
      { id: "117-6", text: "de", category: WordClass.PREPOSICION },
      { id: "117-7", text: "Chimalistac", category: WordClass.SUSTANTIVO },
      { id: "117-8", text: "allá", category: WordClass.ADVERBIO },
      { id: "117-9", text: "por", category: WordClass.PREPOSICION },
      { id: "117-10", text: "los", category: WordClass.DETERMINANTE },
      { id: "117-11", text: "rumbos", category: WordClass.SUSTANTIVO },
      { id: "117-12", text: "de", category: WordClass.PREPOSICION },
      { id: "117-13", text: "San", category: WordClass.SUSTANTIVO },
      { id: "117-14", text: "Ángel", category: WordClass.SUSTANTIVO },
      { id: "117-15", text: "Era", category: WordClass.VERBO },
      { id: "117-16", text: "hija", category: WordClass.SUSTANTIVO },
      { id: "117-17", text: "de", category: WordClass.PREPOSICION },
      { id: "117-18", text: "labradores", category: WordClass.SUSTANTIVO },
      { id: "117-19", text: "honrados", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 118,
    title: "Conversación en La Catedral - Vargas Llosa (Perú)",
    text: "Desde la puerta de La Crónica Santiago mira la avenida Tacna sin amor. Los autos, los edificios desiguales y descoloridos.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 40,
    words: [
      { id: "118-1", text: "Desde", category: WordClass.PREPOSICION },
      { id: "118-2", text: "la", category: WordClass.DETERMINANTE },
      { id: "118-3", text: "puerta", category: WordClass.SUSTANTIVO },
      { id: "118-4", text: "de", category: WordClass.PREPOSICION },
      { id: "118-5", text: "La", category: WordClass.DETERMINANTE },
      { id: "118-6", text: "Crónica", category: WordClass.SUSTANTIVO },
      { id: "118-7", text: "Santiago", category: WordClass.SUSTANTIVO },
      { id: "118-8", text: "mira", category: WordClass.VERBO },
      { id: "118-9", text: "la", category: WordClass.DETERMINANTE },
      { id: "118-10", text: "avenida", category: WordClass.SUSTANTIVO },
      { id: "118-11", text: "Tacna", category: WordClass.SUSTANTIVO },
      { id: "118-12", text: "sin", category: WordClass.PREPOSICION },
      { id: "118-13", text: "amor", category: WordClass.SUSTANTIVO },
      { id: "118-14", text: "Los", category: WordClass.DETERMINANTE },
      { id: "118-15", text: "autos", category: WordClass.SUSTANTIVO },
      { id: "118-16", text: "los", category: WordClass.DETERMINANTE },
      { id: "118-17", text: "edificios", category: WordClass.SUSTANTIVO },
      { id: "118-18", text: "desiguales", category: WordClass.ADJETIVO },
      { id: "118-19", text: "y", category: WordClass.CONJUNCION },
      { id: "118-20", text: "descoloridos", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 119,
    title: "Fervor de Buenos Aires - Borges (Argentina)",
    text: "Las calles de Buenos Aires ya son mi entraña. No las ávidas calles incómodas del trajín, sino las calles desganadas del barrio.",
    targetCategory: WordClass.VERBO,
    timeLimit: 40,
    words: [
      { id: "119-1", text: "Las", category: WordClass.DETERMINANTE },
      { id: "119-2", text: "calles", category: WordClass.SUSTANTIVO },
      { id: "119-3", text: "de", category: WordClass.PREPOSICION },
      { id: "119-4", text: "Buenos", category: WordClass.SUSTANTIVO },
      { id: "119-5", text: "Aires", category: WordClass.SUSTANTIVO },
      { id: "119-6", text: "ya", category: WordClass.ADVERBIO },
      { id: "119-7", text: "son", category: WordClass.VERBO },
      { id: "119-8", text: "mi", category: WordClass.DETERMINANTE },
      { id: "119-9", text: "entraña", category: WordClass.SUSTANTIVO },
      { id: "119-10", text: "No", category: WordClass.ADVERBIO },
      { id: "119-11", text: "las", category: WordClass.DETERMINANTE },
      { id: "119-12", text: "ávidas", category: WordClass.ADJETIVO },
      { id: "119-13", text: "calles", category: WordClass.SUSTANTIVO },
      { id: "119-14", text: "incómodas", category: WordClass.ADJETIVO },
      { id: "119-15", text: "del", category: WordClass.PREPOSICION },
      { id: "119-16", text: "trajín", category: WordClass.SUSTANTIVO },
      { id: "119-17", text: "sino", category: WordClass.CONJUNCION },
      { id: "119-18", text: "las", category: WordClass.DETERMINANTE },
      { id: "119-19", text: "calles", category: WordClass.SUSTANTIVO },
      { id: "119-20", text: "desganadas", category: WordClass.ADJETIVO },
      { id: "119-21", text: "del", category: WordClass.PREPOSICION },
      { id: "119-22", text: "barrio", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 120,
    title: "El llano en llamas - Rulfo (México)",
    text: "Nos habían dado la tierra. Y nos la habían dado en aquel lugar donde ni los conejos corrían.",
    targetCategory: WordClass.CONJUNCION,
    timeLimit: 35,
    words: [
      { id: "120-1", text: "Nos", category: WordClass.PRONOMBRE },
      { id: "120-2", text: "habían", category: WordClass.VERBO },
      { id: "120-3", text: "dado", category: WordClass.VERBO },
      { id: "120-4", text: "la", category: WordClass.DETERMINANTE },
      { id: "120-5", text: "tierra", category: WordClass.SUSTANTIVO },
      { id: "120-6", text: "Y", category: WordClass.CONJUNCION },
      { id: "120-7", text: "nos", category: WordClass.PRONOMBRE },
      { id: "120-8", text: "la", category: WordClass.PRONOMBRE },
      { id: "120-9", text: "habían", category: WordClass.VERBO },
      { id: "120-10", text: "dado", category: WordClass.VERBO },
      { id: "120-11", text: "en", category: WordClass.PREPOSICION },
      { id: "120-12", text: "aquel", category: WordClass.DETERMINANTE },
      { id: "120-13", text: "lugar", category: WordClass.SUSTANTIVO },
      { id: "120-14", text: "donde", category: WordClass.ADVERBIO },
      { id: "120-15", text: "ni", category: WordClass.CONJUNCION },
      { id: "120-16", text: "los", category: WordClass.DETERMINANTE },
      { id: "120-17", text: "conejos", category: WordClass.SUSTANTIVO },
      { id: "120-18", text: "corrían", category: WordClass.VERBO },
    ]
  },
  {
    id: 121,
    title: "Canaima - Gallegos (Venezuela)",
    text: "Marcos Vargas llegó al caney cuando ya el sol estaba alto. Traía noticias de los hombres que trabajaban río arriba.",
    targetCategory: WordClass.ADVERBIO,
    timeLimit: 35,
    words: [
      { id: "121-1", text: "Marcos", category: WordClass.SUSTANTIVO },
      { id: "121-2", text: "Vargas", category: WordClass.SUSTANTIVO },
      { id: "121-3", text: "llegó", category: WordClass.VERBO },
      { id: "121-4", text: "al", category: WordClass.PREPOSICION },
      { id: "121-5", text: "caney", category: WordClass.SUSTANTIVO },
      { id: "121-6", text: "cuando", category: WordClass.CONJUNCION },
      { id: "121-7", text: "ya", category: WordClass.ADVERBIO },
      { id: "121-8", text: "el", category: WordClass.DETERMINANTE },
      { id: "121-9", text: "sol", category: WordClass.SUSTANTIVO },
      { id: "121-10", text: "estaba", category: WordClass.VERBO },
      { id: "121-11", text: "alto", category: WordClass.ADJETIVO },
      { id: "121-12", text: "Traía", category: WordClass.VERBO },
      { id: "121-13", text: "noticias", category: WordClass.SUSTANTIVO },
      { id: "121-14", text: "de", category: WordClass.PREPOSICION },
      { id: "121-15", text: "los", category: WordClass.DETERMINANTE },
      { id: "121-16", text: "hombres", category: WordClass.SUSTANTIVO },
      { id: "121-17", text: "que", category: WordClass.PRONOMBRE },
      { id: "121-18", text: "trabajaban", category: WordClass.VERBO },
      { id: "121-19", text: "río", category: WordClass.SUSTANTIVO },
      { id: "121-20", text: "arriba", category: WordClass.ADVERBIO },
    ]
  },
  {
    id: 122,
    title: "El mundo es ancho y ajeno - Alegría (Perú)",
    text: "La comunidad de Rumi tiene tierras desde hace tiempo inmemorial. Allí nacieron y murieron muchas generaciones de indios laboriosos.",
    targetCategory: WordClass.DETERMINANTE,
    timeLimit: 40,
    words: [
      { id: "122-1", text: "La", category: WordClass.DETERMINANTE },
      { id: "122-2", text: "comunidad", category: WordClass.SUSTANTIVO },
      { id: "122-3", text: "de", category: WordClass.PREPOSICION },
      { id: "122-4", text: "Rumi", category: WordClass.SUSTANTIVO },
      { id: "122-5", text: "tiene", category: WordClass.VERBO },
      { id: "122-6", text: "tierras", category: WordClass.SUSTANTIVO },
      { id: "122-7", text: "desde", category: WordClass.PREPOSICION },
      { id: "122-8", text: "hace", category: WordClass.VERBO },
      { id: "122-9", text: "tiempo", category: WordClass.SUSTANTIVO },
      { id: "122-10", text: "inmemorial", category: WordClass.ADJETIVO },
      { id: "122-11", text: "Allí", category: WordClass.ADVERBIO },
      { id: "122-12", text: "nacieron", category: WordClass.VERBO },
      { id: "122-13", text: "y", category: WordClass.CONJUNCION },
      { id: "122-14", text: "murieron", category: WordClass.VERBO },
      { id: "122-15", text: "muchas", category: WordClass.DETERMINANTE },
      { id: "122-16", text: "generaciones", category: WordClass.SUSTANTIVO },
      { id: "122-17", text: "de", category: WordClass.PREPOSICION },
      { id: "122-18", text: "indios", category: WordClass.SUSTANTIVO },
      { id: "122-19", text: "laboriosos", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 123,
    title: "Los ríos profundos - Arguedas (Perú)",
    text: "Infundía respeto, a pesar de su anticuada y sucia apariencia. Las personas principales del Cuzco lo saludaban seriamente.",
    targetCategory: WordClass.PRONOMBRE,
    timeLimit: 35,
    words: [
      { id: "123-1", text: "Infundía", category: WordClass.VERBO },
      { id: "123-2", text: "respeto", category: WordClass.SUSTANTIVO },
      { id: "123-3", text: "a", category: WordClass.PREPOSICION },
      { id: "123-4", text: "pesar", category: WordClass.SUSTANTIVO },
      { id: "123-5", text: "de", category: WordClass.PREPOSICION },
      { id: "123-6", text: "su", category: WordClass.DETERMINANTE },
      { id: "123-7", text: "anticuada", category: WordClass.ADJETIVO },
      { id: "123-8", text: "y", category: WordClass.CONJUNCION },
      { id: "123-9", text: "sucia", category: WordClass.ADJETIVO },
      { id: "123-10", text: "apariencia", category: WordClass.SUSTANTIVO },
      { id: "123-11", text: "Las", category: WordClass.DETERMINANTE },
      { id: "123-12", text: "personas", category: WordClass.SUSTANTIVO },
      { id: "123-13", text: "principales", category: WordClass.ADJETIVO },
      { id: "123-14", text: "del", category: WordClass.PREPOSICION },
      { id: "123-15", text: "Cuzco", category: WordClass.SUSTANTIVO },
      { id: "123-16", text: "lo", category: WordClass.PRONOMBRE },
      { id: "123-17", text: "saludaban", category: WordClass.VERBO },
      { id: "123-18", text: "seriamente", category: WordClass.ADVERBIO },
    ]
  },
  {
    id: 124,
    title: "La colmena - Cela (España)",
    text: "Doña Rosa va y viene por entre las mesas del café, tropezando con los clientes que beben su chocolate espeso.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 35,
    words: [
      { id: "124-1", text: "Doña", category: WordClass.SUSTANTIVO },
      { id: "124-2", text: "Rosa", category: WordClass.SUSTANTIVO },
      { id: "124-3", text: "va", category: WordClass.VERBO },
      { id: "124-4", text: "y", category: WordClass.CONJUNCION },
      { id: "124-5", text: "viene", category: WordClass.VERBO },
      { id: "124-6", text: "por", category: WordClass.PREPOSICION },
      { id: "124-7", text: "entre", category: WordClass.PREPOSICION },
      { id: "124-8", text: "las", category: WordClass.DETERMINANTE },
      { id: "124-9", text: "mesas", category: WordClass.SUSTANTIVO },
      { id: "124-10", text: "del", category: WordClass.PREPOSICION },
      { id: "124-11", text: "café", category: WordClass.SUSTANTIVO },
      { id: "124-12", text: "tropezando", category: WordClass.VERBO },
      { id: "124-13", text: "con", category: WordClass.PREPOSICION },
      { id: "124-14", text: "los", category: WordClass.DETERMINANTE },
      { id: "124-15", text: "clientes", category: WordClass.SUSTANTIVO },
      { id: "124-16", text: "que", category: WordClass.PRONOMBRE },
      { id: "124-17", text: "beben", category: WordClass.VERBO },
      { id: "124-18", text: "su", category: WordClass.DETERMINANTE },
      { id: "124-19", text: "chocolate", category: WordClass.SUSTANTIVO },
      { id: "124-20", text: "espeso", category: WordClass.ADJETIVO },
    ]
  },
  {
      id: 125,
    title: "Don Quijote - Cervantes",
    categoryGroup: 'Literatura en español',
    text: "En un lugar de la Mancha de cuyo nombre no quiero acordarme.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 25,
    words: [
      { id: "DQ-1", text: "En", category: WordClass.PREPOSICION },
      { id: "DQ-2", text: "un", category: WordClass.DETERMINANTE },
      { id: "DQ-3", text: "lugar", category: WordClass.SUSTANTIVO },
      { id: "DQ-4", text: "de", category: WordClass.PREPOSICION },
      { id: "DQ-5", text: "la", category: WordClass.DETERMINANTE },
      { id: "DQ-6", text: "Mancha", category: WordClass.SUSTANTIVO },
      { id: "DQ-7", text: "de", category: WordClass.PREPOSICION },
      { id: "DQ-8", text: "cuyo", category: WordClass.DETERMINANTE },
      { id: "DQ-9", text: "nombre", category: WordClass.SUSTANTIVO },
      { id: "DQ-10", text: "no", category: WordClass.ADVERBIO },
      { id: "DQ-11", text: "quiero", category: WordClass.VERBO },
      { id: "DQ-12", text: "acordarme.", category: WordClass.VERBO },
    ]
  },
  {
      id: 126,
    title: "Rimas VII - Bécquer",
    categoryGroup: 'Literatura en español',
    text: "Del salón en el ángulo oscuro de su dueña tal vez olvidada.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 30,
    words: [
      { id: "BEC-1", text: "Del", category: WordClass.PREPOSICION },
      { id: "BEC-2", text: "salón", category: WordClass.SUSTANTIVO },
      { id: "BEC-3", text: "en", category: WordClass.PREPOSICION },
      { id: "BEC-4", text: "el", category: WordClass.DETERMINANTE },
      { id: "BEC-5", text: "ángulo", category: WordClass.SUSTANTIVO },
      { id: "BEC-6", text: "oscuro", category: WordClass.ADJETIVO },
      { id: "BEC-7", text: "de", category: WordClass.PREPOSICION },
      { id: "BEC-8", text: "su", category: WordClass.DETERMINANTE },
      { id: "BEC-9", text: "dueña", category: WordClass.SUSTANTIVO },
      { id: "BEC-10", text: "tal", category: WordClass.ADVERBIO },
      { id: "BEC-11", text: "vez", category: WordClass.SUSTANTIVO },
      { id: "BEC-12", text: "olvidada.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 126,
    title: "Tiempo de silencio - Martín-Santos (España)",
    text: "Había una vez un rey que tenía tres hijas. Las tres eran hermosas pero la menor era la más bella de todas.",
    targetCategory: WordClass.VERBO,
    timeLimit: 40,
    words: [
      { id: "126-1", text: "Había", category: WordClass.VERBO },
      { id: "126-2", text: "una", category: WordClass.DETERMINANTE },
      { id: "126-3", text: "vez", category: WordClass.SUSTANTIVO },
      { id: "126-4", text: "un", category: WordClass.DETERMINANTE },
      { id: "126-5", text: "rey", category: WordClass.SUSTANTIVO },
      { id: "126-6", text: "que", category: WordClass.PRONOMBRE },
      { id: "126-7", text: "tenía", category: WordClass.VERBO },
      { id: "126-8", text: "tres", category: WordClass.DETERMINANTE },
      { id: "126-9", text: "hijas", category: WordClass.SUSTANTIVO },
      { id: "126-10", text: "Las", category: WordClass.DETERMINANTE },
      { id: "126-11", text: "tres", category: WordClass.DETERMINANTE },
      { id: "126-12", text: "eran", category: WordClass.VERBO },
      { id: "126-13", text: "hermosas", category: WordClass.ADJETIVO },
      { id: "126-14", text: "pero", category: WordClass.CONJUNCION },
      { id: "126-15", text: "la", category: WordClass.DETERMINANTE },
      { id: "126-16", text: "menor", category: WordClass.ADJETIVO },
      { id: "126-17", text: "era", category: WordClass.VERBO },
      { id: "126-18", text: "la", category: WordClass.DETERMINANTE },
      { id: "126-19", text: "más", category: WordClass.ADVERBIO },
      { id: "126-20", text: "bella", category: WordClass.ADJETIVO },
      { id: "126-21", text: "de", category: WordClass.PREPOSICION },
      { id: "126-22", text: "todas", category: WordClass.PRONOMBRE },
    ]
  },
  {
    id: 127,
    title: "Campos de Castilla - Machado",
    categoryGroup: 'Literatura en español',
    text: "He andado muchos caminos he abierto muchas veredas.",
    targetCategory: WordClass.VERBO,
    timeLimit: 30,
    words: [
      { id: "MAC-1", text: "He", category: WordClass.VERBO },
      { id: "MAC-2", text: "andado", category: WordClass.VERBO },
      { id: "MAC-3", text: "muchos", category: WordClass.DETERMINANTE },
      { id: "MAC-4", text: "caminos", category: WordClass.SUSTANTIVO },
      { id: "MAC-5", text: "he", category: WordClass.VERBO },
      { id: "MAC-6", text: "abierto", category: WordClass.VERBO },
      { id: "MAC-7", text: "muchas", category: WordClass.DETERMINANTE },
      { id: "MAC-8", text: "veredas.", category: WordClass.SUSTANTIVO },
    ]
  }
];

export const LITERARY_UNIVERSAL_LEVELS: Level[] = [
  {
    id: 201,
    title: "El Principito - Saint-Exupéry",
    categoryGroup: 'Literatura universal',
    text: "Todas las personas mayores fueron primero niños aunque pocas de ellas lo recuerden.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 30,
    words: [
      { id: "EP-1", text: "Todas", category: WordClass.DETERMINANTE },
      { id: "EP-2", text: "las", category: WordClass.DETERMINANTE },
      { id: "EP-3", text: "personas", category: WordClass.SUSTANTIVO },
      { id: "EP-4", text: "mayores", category: WordClass.ADJETIVO },
      { id: "EP-5", text: "fueron", category: WordClass.VERBO },
      { id: "EP-6", text: "primero", category: WordClass.ADVERBIO },
      { id: "EP-7", text: "niños", category: WordClass.SUSTANTIVO },
      { id: "EP-8", text: "aunque", category: WordClass.CONJUNCION },
      { id: "EP-9", text: "pocas", category: WordClass.DETERMINANTE },
      { id: "EP-10", text: "de", category: WordClass.PREPOSICION },
      { id: "EP-11", text: "ellas", category: WordClass.PRONOMBRE },
      { id: "EP-12", text: "lo", category: WordClass.PRONOMBRE },
      { id: "EP-13", text: "recuerden.", category: WordClass.VERBO },
    ]
  },
  {
    id: 202,
    title: "1984 - George Orwell",
    categoryGroup: 'Literatura universal',
    text: "Era un día luminoso y frío de abril y los relojes daban las trece.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 25,
    words: [
      { id: "OR-1", text: "Era", category: WordClass.VERBO },
      { id: "OR-2", text: "un", category: WordClass.DETERMINANTE },
      { id: "OR-3", text: "día", category: WordClass.SUSTANTIVO },
      { id: "OR-4", text: "luminoso", category: WordClass.ADJETIVO },
      { id: "OR-5", text: "y", category: WordClass.CONJUNCION },
      { id: "OR-6", text: "frío", category: WordClass.ADJETIVO },
      { id: "OR-7", text: "de", category: WordClass.PREPOSICION },
      { id: "OR-8", text: "abril", category: WordClass.SUSTANTIVO },
      { id: "OR-9", text: "y", category: WordClass.CONJUNCION },
      { id: "OR-10", text: "los", category: WordClass.DETERMINANTE },
      { id: "OR-11", text: "relojes", category: WordClass.SUSTANTIVO },
      { id: "OR-12", text: "daban", category: WordClass.VERBO },
      { id: "OR-13", text: "las", category: WordClass.DETERMINANTE },
      { id: "OR-14", text: "trece.", category: WordClass.DETERMINANTE },
    ]
  },
  {
    id: 203,
    title: "Hamlet - Shakespeare",
    categoryGroup: 'Literatura universal',
    text: "Ser o no ser esa es la cuestión.",
    targetCategory: WordClass.VERBO,
    timeLimit: 20,
    words: [
      { id: "HAM-1", text: "Ser", category: WordClass.VERBO },
      { id: "HAM-2", text: "o", category: WordClass.CONJUNCION },
      { id: "HAM-3", text: "no", category: WordClass.ADVERBIO },
      { id: "HAM-4", text: "ser", category: WordClass.VERBO },
      { id: "HAM-5", text: "esa", category: WordClass.PRONOMBRE },
      { id: "HAM-6", text: "es", category: WordClass.VERBO },
      { id: "HAM-7", text: "la", category: WordClass.DETERMINANTE },
      { id: "HAM-8", text: "cuestión.", category: WordClass.SUSTANTIVO },
    ]
  },
{
    id: 204,
    title: "Otra vuelta de tuerca - Henry James",
    categoryGroup: 'Literatura universal',
    text: "La historia nos había mantenido alrededor del fuego suficientemente sin aliento pero salvo el comentario evidente de que era espantosa nadie habló hasta que nos pusimos de pie.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 45,
    words: [
      { id: "OVT-1", text: "La", category: WordClass.DETERMINANTE },
      { id: "OVT-2", text: "historia", category: WordClass.SUSTANTIVO },
      { id: "OVT-3", text: "nos", category: WordClass.PRONOMBRE },
      { id: "OVT-4", text: "había", category: WordClass.VERBO },
      { id: "OVT-5", text: "mantenido", category: WordClass.VERBO },
      { id: "OVT-6", text: "alrededor", category: WordClass.ADVERBIO },
      { id: "OVT-7", text: "del", category: WordClass.PREPOSICION },
      { id: "OVT-8", text: "fuego", category: WordClass.SUSTANTIVO },
      { id: "OVT-9", text: "suficientemente", category: WordClass.ADVERBIO },
      { id: "OVT-10", text: "sin", category: WordClass.PREPOSICION },
      { id: "OVT-11", text: "aliento", category: WordClass.SUSTANTIVO },
      { id: "OVT-12", text: "pero", category: WordClass.CONJUNCION },
      { id: "OVT-13", text: "salvo", category: WordClass.PREPOSICION },
      { id: "OVT-14", text: "el", category: WordClass.DETERMINANTE },
      { id: "OVT-15", text: "comentario", category: WordClass.SUSTANTIVO },
      { id: "OVT-16", text: "evidente", category: WordClass.ADJETIVO },
      { id: "OVT-17", text: "de", category: WordClass.PREPOSICION },
      { id: "OVT-18", text: "que", category: WordClass.CONJUNCION },
      { id: "OVT-19", text: "era", category: WordClass.VERBO },
      { id: "OVT-20", text: "espantosa", category: WordClass.ADJETIVO },
      { id: "OVT-21", text: "nadie", category: WordClass.PRONOMBRE },
      { id: "OVT-22", text: "habló", category: WordClass.VERBO },
      { id: "OVT-23", text: "hasta", category: WordClass.PREPOSICION },
      { id: "OVT-24", text: "que", category: WordClass.CONJUNCION },
      { id: "OVT-25", text: "nos", category: WordClass.PRONOMBRE },
      { id: "OVT-26", text: "pusimos", category: WordClass.VERBO },
      { id: "OVT-27", text: "de", category: WordClass.PREPOSICION },
      { id: "OVT-28", text: "pie.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 205,
    title: "Orgullo y prejuicio - Jane Austen",
    categoryGroup: 'Literatura universal',
    text: "Es una verdad universalmente reconocida que un hombre soltero en posesión de fortuna necesita esposa.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 40,
    words: [
      { id: "OYP-1", text: "Es", category: WordClass.VERBO },
      { id: "OYP-2", text: "una", category: WordClass.DETERMINANTE },
      { id: "OYP-3", text: "verdad", category: WordClass.SUSTANTIVO },
      { id: "OYP-4", text: "universalmente", category: WordClass.ADVERBIO },
      { id: "OYP-5", text: "reconocida", category: WordClass.ADJETIVO },
      { id: "OYP-6", text: "que", category: WordClass.CONJUNCION },
      { id: "OYP-7", text: "un", category: WordClass.DETERMINANTE },
      { id: "OYP-8", text: "hombre", category: WordClass.SUSTANTIVO },
      { id: "OYP-9", text: "soltero", category: WordClass.ADJETIVO },
      { id: "OYP-10", text: "en", category: WordClass.PREPOSICION },
      { id: "OYP-11", text: "posesión", category: WordClass.SUSTANTIVO },
      { id: "OYP-12", text: "de", category: WordClass.PREPOSICION },
      { id: "OYP-13", text: "fortuna", category: WordClass.SUSTANTIVO },
      { id: "OYP-14", text: "necesita", category: WordClass.VERBO },
      { id: "OYP-15", text: "esposa.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 206,
    title: "Moby Dick - Herman Melville",
    categoryGroup: 'Literatura universal',
    text: "Llamadme Ismael.",
    targetCategory: WordClass.VERBO,
    timeLimit: 15,
    words: [
      { id: "MD-1", text: "Llamadme", category: WordClass.VERBO },
      { id: "MD-2", text: "Ismael.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 207,
    title: "La metamorfosis - Franz Kafka",
    categoryGroup: 'Literatura universal',
    text: "Una mañana tras un sueño intranquilo Gregorio Samsa se despertó convertido en un monstruoso insecto.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 35,
    words: [
      { id: "MET-1", text: "Una", category: WordClass.DETERMINANTE },
      { id: "MET-2", text: "mañana", category: WordClass.SUSTANTIVO },
      { id: "MET-3", text: "tras", category: WordClass.PREPOSICION },
      { id: "MET-4", text: "un", category: WordClass.DETERMINANTE },
      { id: "MET-5", text: "sueño", category: WordClass.SUSTANTIVO },
      { id: "MET-6", text: "intranquilo", category: WordClass.ADJETIVO },
      { id: "MET-7", text: "Gregorio", category: WordClass.SUSTANTIVO },
      { id: "MET-8", text: "Samsa", category: WordClass.SUSTANTIVO },
      { id: "MET-9", text: "se", category: WordClass.PRONOMBRE },
      { id: "MET-10", text: "despertó", category: WordClass.VERBO },
      { id: "MET-11", text: "convertido", category: WordClass.VERBO },
      { id: "MET-12", text: "en", category: WordClass.PREPOSICION },
      { id: "MET-13", text: "un", category: WordClass.DETERMINANTE },
      { id: "MET-14", text: "monstruoso", category: WordClass.ADJETIVO },
      { id: "MET-15", text: "insecto.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 208,
    title: "En busca del tiempo perdido - Marcel Proust",
    categoryGroup: 'Literatura universal',
    text: "Durante mucho tiempo me acosté temprano.",
    targetCategory: WordClass.ADVERBIO,
    timeLimit: 20,
    words: [
      { id: "BTP-1", text: "Durante", category: WordClass.PREPOSICION },
      { id: "BTP-2", text: "mucho", category: WordClass.DETERMINANTE },
      { id: "BTP-3", text: "tiempo", category: WordClass.SUSTANTIVO },
      { id: "BTP-4", text: "me", category: WordClass.PRONOMBRE },
      { id: "BTP-5", text: "acosté", category: WordClass.VERBO },
      { id: "BTP-6", text: "temprano.", category: WordClass.ADVERBIO },
    ]
  },
  {
    id: 209,
    title: "El gran Gatsby - F. Scott Fitzgerald",
    categoryGroup: 'Literatura universal',
    text: "En mis años más vulnerables mi padre me dio un consejo que nunca olvidé.",
    targetCategory: WordClass.PRONOMBRE,
    timeLimit: 30,
    words: [
      { id: "GG-1", text: "En", category: WordClass.PREPOSICION },
      { id: "GG-2", text: "mis", category: WordClass.DETERMINANTE },
      { id: "GG-3", text: "años", category: WordClass.SUSTANTIVO },
      { id: "GG-4", text: "más", category: WordClass.ADVERBIO },
      { id: "GG-5", text: "vulnerables", category: WordClass.ADJETIVO },
      { id: "GG-6", text: "mi", category: WordClass.DETERMINANTE },
      { id: "GG-7", text: "padre", category: WordClass.SUSTANTIVO },
      { id: "GG-8", text: "me", category: WordClass.PRONOMBRE },
      { id: "GG-9", text: "dio", category: WordClass.VERBO },
      { id: "GG-10", text: "un", category: WordClass.DETERMINANTE },
      { id: "GG-11", text: "consejo", category: WordClass.SUSTANTIVO },
      { id: "GG-12", text: "que", category: WordClass.PRONOMBRE },
      { id: "GG-13", text: "nunca", category: WordClass.ADVERBIO },
      { id: "GG-14", text: "olvidé.", category: WordClass.VERBO },
    ]
  },
  {
    id: 210,
    title: "Crimen y castigo - Dostoievski",
    categoryGroup: 'Literatura universal',
    text: "A principios de julio hacía un calor extraordinario en las calles sofocantes de la ciudad.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 35,
    words: [
      { id: "CC-1", text: "A", category: WordClass.PREPOSICION },
      { id: "CC-2", text: "principios", category: WordClass.SUSTANTIVO },
      { id: "CC-3", text: "de", category: WordClass.PREPOSICION },
      { id: "CC-4", text: "julio", category: WordClass.SUSTANTIVO },
      { id: "CC-5", text: "hacía", category: WordClass.VERBO },
      { id: "CC-6", text: "un", category: WordClass.DETERMINANTE },
      { id: "CC-7", text: "calor", category: WordClass.SUSTANTIVO },
      { id: "CC-8", text: "extraordinario", category: WordClass.ADJETIVO },
      { id: "CC-9", text: "en", category: WordClass.PREPOSICION },
      { id: "CC-10", text: "las", category: WordClass.DETERMINANTE },
      { id: "CC-11", text: "calles", category: WordClass.SUSTANTIVO },
      { id: "CC-12", text: "sofocantes", category: WordClass.ADJETIVO },
      { id: "CC-13", text: "de", category: WordClass.PREPOSICION },
      { id: "CC-14", text: "la", category: WordClass.DETERMINANTE },
      { id: "CC-15", text: "ciudad.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 211,
    title: "El extranjero - Albert Camus",
    categoryGroup: 'Literatura universal',
    text: "Hoy ha muerto mamá o quizás ayer no lo sé.",
    targetCategory: WordClass.VERBO,
    timeLimit: 25,
    words: [
      { id: "EXT-1", text: "Hoy", category: WordClass.ADVERBIO },
      { id: "EXT-2", text: "ha", category: WordClass.VERBO },
      { id: "EXT-3", text: "muerto", category: WordClass.VERBO },
      { id: "EXT-4", text: "mamá", category: WordClass.SUSTANTIVO },
      { id: "EXT-5", text: "o", category: WordClass.CONJUNCION },
      { id: "EXT-6", text: "quizás", category: WordClass.ADVERBIO },
      { id: "EXT-7", text: "ayer", category: WordClass.ADVERBIO },
      { id: "EXT-8", text: "no", category: WordClass.ADVERBIO },
      { id: "EXT-9", text: "lo", category: WordClass.PRONOMBRE },
      { id: "EXT-10", text: "sé.", category: WordClass.VERBO },
    ]
  },
  {
    id: 212,
    title: "Ana Karenina - Lev Tolstói",
    categoryGroup: 'Literatura universal',
    text: "Todas las familias felices se parecen unas a otras cada familia infeliz lo es a su manera.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 40,
    words: [
      { id: "AK-1", text: "Todas", category: WordClass.DETERMINANTE },
      { id: "AK-2", text: "las", category: WordClass.DETERMINANTE },
      { id: "AK-3", text: "familias", category: WordClass.SUSTANTIVO },
      { id: "AK-4", text: "felices", category: WordClass.ADJETIVO },
      { id: "AK-5", text: "se", category: WordClass.PRONOMBRE },
      { id: "AK-6", text: "parecen", category: WordClass.VERBO },
      { id: "AK-7", text: "unas", category: WordClass.PRONOMBRE },
      { id: "AK-8", text: "a", category: WordClass.PREPOSICION },
      { id: "AK-9", text: "otras", category: WordClass.PRONOMBRE },
      { id: "AK-10", text: "cada", category: WordClass.DETERMINANTE },
      { id: "AK-11", text: "familia", category: WordClass.SUSTANTIVO },
      { id: "AK-12", text: "infeliz", category: WordClass.ADJETIVO },
      { id: "AK-13", text: "lo", category: WordClass.PRONOMBRE },
      { id: "AK-14", text: "es", category: WordClass.VERBO },
      { id: "AK-15", text: "a", category: WordClass.PREPOSICION },
      { id: "AK-16", text: "su", category: WordClass.DETERMINANTE },
      { id: "AK-17", text: "manera.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 213,
    title: "Ulises - James Joyce",
    categoryGroup: 'Literatura universal',
    text: "Majestuoso y rollizo Buck Mulligan apareció en lo alto de la escalera.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 30,
    words: [
      { id: "UL-1", text: "Majestuoso", category: WordClass.ADJETIVO },
      { id: "UL-2", text: "y", category: WordClass.CONJUNCION },
      { id: "UL-3", text: "rollizo", category: WordClass.ADJETIVO },
      { id: "UL-4", text: "Buck", category: WordClass.SUSTANTIVO },
      { id: "UL-5", text: "Mulligan", category: WordClass.SUSTANTIVO },
      { id: "UL-6", text: "apareció", category: WordClass.VERBO },
      { id: "UL-7", text: "en", category: WordClass.PREPOSICION },
      { id: "UL-8", text: "lo", category: WordClass.DETERMINANTE },
      { id: "UL-9", text: "alto", category: WordClass.ADJETIVO },
      { id: "UL-10", text: "de", category: WordClass.PREPOSICION },
      { id: "UL-11", text: "la", category: WordClass.DETERMINANTE },
      { id: "UL-12", text: "escalera.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 214,
    title: "La Odisea - Homero",
    categoryGroup: 'Literatura universal',
    text: "Cuéntame musa la historia del hombre de muchos senderos.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 25,
    words: [
      { id: "OD-1", text: "Cuéntame", category: WordClass.VERBO },
      { id: "OD-2", text: "musa", category: WordClass.SUSTANTIVO },
      { id: "OD-3", text: "la", category: WordClass.DETERMINANTE },
      { id: "OD-4", text: "historia", category: WordClass.SUSTANTIVO },
      { id: "OD-5", text: "del", category: WordClass.PREPOSICION },
      { id: "OD-6", text: "hombre", category: WordClass.SUSTANTIVO },
      { id: "OD-7", text: "de", category: WordClass.PREPOSICION },
      { id: "OD-8", text: "muchos", category: WordClass.DETERMINANTE },
      { id: "OD-9", text: "senderos.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 215,
    title: "Lolita - Vladimir Nabokov",
    categoryGroup: 'Literatura universal',
    text: "Lolita luz de mi vida fuego de mis entrañas.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 20,
    words: [
      { id: "LOL-1", text: "Lolita", category: WordClass.SUSTANTIVO },
      { id: "LOL-2", text: "luz", category: WordClass.SUSTANTIVO },
      { id: "LOL-3", text: "de", category: WordClass.PREPOSICION },
      { id: "LOL-4", text: "mi", category: WordClass.DETERMINANTE },
      { id: "LOL-5", text: "vida", category: WordClass.SUSTANTIVO },
      { id: "LOL-6", text: "fuego", category: WordClass.SUSTANTIVO },
      { id: "LOL-7", text: "de", category: WordClass.PREPOSICION },
      { id: "LOL-8", text: "mis", category: WordClass.DETERMINANTE },
      { id: "LOL-9", text: "entrañas.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 216,
    title: "Madame Bovary - Gustave Flaubert",
    categoryGroup: 'Literatura universal',
    text: "Estábamos en clase cuando entró el director seguido de un nuevo alumno vestido de paisano.",
    targetCategory: WordClass.VERBO,
    timeLimit: 35,
    words: [
      { id: "MB-1", text: "Estábamos", category: WordClass.VERBO },
      { id: "MB-2", text: "en", category: WordClass.PREPOSICION },
      { id: "MB-3", text: "clase", category: WordClass.SUSTANTIVO },
      { id: "MB-4", text: "cuando", category: WordClass.CONJUNCION },
      { id: "MB-5", text: "entró", category: WordClass.VERBO },
      { id: "MB-6", text: "el", category: WordClass.DETERMINANTE },
      { id: "MB-7", text: "director", category: WordClass.SUSTANTIVO },
      { id: "MB-8", text: "seguido", category: WordClass.VERBO },
      { id: "MB-9", text: "de", category: WordClass.PREPOSICION },
      { id: "MB-10", text: "un", category: WordClass.DETERMINANTE },
      { id: "MB-11", text: "nuevo", category: WordClass.ADJETIVO },
      { id: "MB-12", text: "alumno", category: WordClass.SUSTANTIVO },
      { id: "MB-13", text: "vestido", category: WordClass.VERBO },
      { id: "MB-14", text: "de", category: WordClass.PREPOSICION },
      { id: "MB-15", text: "paisano.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 217,
    title: "El guardián entre el centeno - J.D. Salinger",
    categoryGroup: 'Literatura universal',
    text: "Si de verdad les interesa lo que voy a contarles lo primero que querrán saber es dónde nací.",
    targetCategory: WordClass.PRONOMBRE,
    timeLimit: 40,
    words: [
      { id: "GC-1", text: "Si", category: WordClass.CONJUNCION },
      { id: "GC-2", text: "de", category: WordClass.PREPOSICION },
      { id: "GC-3", text: "verdad", category: WordClass.SUSTANTIVO },
      { id: "GC-4", text: "les", category: WordClass.PRONOMBRE },
      { id: "GC-5", text: "interesa", category: WordClass.VERBO },
      { id: "GC-6", text: "lo", category: WordClass.PRONOMBRE },
      { id: "GC-7", text: "que", category: WordClass.PRONOMBRE },
      { id: "GC-8", text: "voy", category: WordClass.VERBO },
      { id: "GC-9", text: "a", category: WordClass.PREPOSICION },
      { id: "GC-10", text: "contarles", category: WordClass.VERBO },
      { id: "GC-11", text: "lo", category: WordClass.DETERMINANTE },
      { id: "GC-12", text: "primero", category: WordClass.ADJETIVO },
      { id: "GC-13", text: "que", category: WordClass.PRONOMBRE },
      { id: "GC-14", text: "querrán", category: WordClass.VERBO },
      { id: "GC-15", text: "saber", category: WordClass.VERBO },
      { id: "GC-16", text: "es", category: WordClass.VERBO },
      { id: "GC-17", text: "dónde", category: WordClass.ADVERBIO },
      { id: "GC-18", text: "nací.", category: WordClass.VERBO },
    ]
  },
  {
    id: 218,
    title: "Los miserables - Victor Hugo",
    categoryGroup: 'Literatura universal',
    text: "Mientras haya sobre la tierra ignorancia y miseria libros como este no serán inútiles.",
    targetCategory: WordClass.CONJUNCION,
    timeLimit: 35,
    words: [
      { id: "MIS-1", text: "Mientras", category: WordClass.CONJUNCION },
      { id: "MIS-2", text: "haya", category: WordClass.VERBO },
      { id: "MIS-3", text: "sobre", category: WordClass.PREPOSICION },
      { id: "MIS-4", text: "la", category: WordClass.DETERMINANTE },
      { id: "MIS-5", text: "tierra", category: WordClass.SUSTANTIVO },
      { id: "MIS-6", text: "ignorancia", category: WordClass.SUSTANTIVO },
      { id: "MIS-7", text: "y", category: WordClass.CONJUNCION },
      { id: "MIS-8", text: "miseria", category: WordClass.SUSTANTIVO },
      { id: "MIS-9", text: "libros", category: WordClass.SUSTANTIVO },
      { id: "MIS-10", text: "como", category: WordClass.CONJUNCION },
      { id: "MIS-11", text: "este", category: WordClass.DETERMINANTE },
      { id: "MIS-12", text: "no", category: WordClass.ADVERBIO },
      { id: "MIS-13", text: "serán", category: WordClass.VERBO },
      { id: "MIS-14", text: "inútiles.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 219,
    title: "Fahrenheit 451 - Ray Bradbury",
    categoryGroup: 'Literatura universal',
    text: "Era un placer quemar.",
    targetCategory: WordClass.VERBO,
    timeLimit: 15,
    words: [
      { id: "F451-1", text: "Era", category: WordClass.VERBO },
      { id: "F451-2", text: "un", category: WordClass.DETERMINANTE },
      { id: "F451-3", text: "placer", category: WordClass.SUSTANTIVO },
      { id: "F451-4", text: "quemar.", category: WordClass.VERBO },
    ]
  },
  {
    id: 220,
    title: "Jane Eyre - Charlotte Brontë",
    categoryGroup: 'Literatura universal',
    text: "Aquel día fue imposible dar un paseo.",
    targetCategory: WordClass.DETERMINANTE,
    timeLimit: 20,
    words: [
      { id: "JE-1", text: "Aquel", category: WordClass.DETERMINANTE },
      { id: "JE-2", text: "día", category: WordClass.SUSTANTIVO },
      { id: "JE-3", text: "fue", category: WordClass.VERBO },
      { id: "JE-4", text: "imposible", category: WordClass.ADJETIVO },
      { id: "JE-5", text: "dar", category: WordClass.VERBO },
      { id: "JE-6", text: "un", category: WordClass.DETERMINANTE },
      { id: "JE-7", text: "paseo.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 221,
    title: "El señor de los anillos - J.R.R. Tolkien",
    categoryGroup: 'Literatura universal',
    text: "Cuando el señor Bilbo Bolsón de Bolsón Cerrado anunció que pronto celebraría su cumpleaños hubo muchas conversaciones.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 45,
    words: [
      { id: "SDA-1", text: "Cuando", category: WordClass.CONJUNCION },
      { id: "SDA-2", text: "el", category: WordClass.DETERMINANTE },
      { id: "SDA-3", text: "señor", category: WordClass.SUSTANTIVO },
      { id: "SDA-4", text: "Bilbo", category: WordClass.SUSTANTIVO },
      { id: "SDA-5", text: "Bolsón", category: WordClass.SUSTANTIVO },
      { id: "SDA-6", text: "de", category: WordClass.PREPOSICION },
      { id: "SDA-7", text: "Bolsón",category: WordClass.SUSTANTIVO },
	{ id: "SDA-8", text: "Cerrado", category: WordClass.SUSTANTIVO },
	{ id: "SDA-9", text: "anunció", category: WordClass.VERBO },
	{ id: "SDA-10", text: "que", category: WordClass.CONJUNCION },
	{ id: "SDA-11", text: "pronto", category: WordClass.ADVERBIO },
	{ id: "SDA-12", text: "celebraría", category: WordClass.VERBO },
	{ id: "SDA-13", text: "su", category: WordClass.DETERMINANTE },
	{ id: "SDA-14", text: "cumpleaños", category: WordClass.SUSTANTIVO },
	{ id: "SDA-15", text: "hubo", category: WordClass.VERBO },
	{ id: "SDA-16", text: "muchas", category: WordClass.DETERMINANTE },
	{ id: "SDA-17", text: "conversaciones.", category: WordClass.SUSTANTIVO },
	]
	},
	{
	id: 222,
	title: "Rayuela - Julio Cortázar",
	categoryGroup: 'Literatura universal',
	text: "Encontraría a la Maga o no la encontraría pero ya no la buscaría.",
	targetCategory: WordClass.VERBO,
	timeLimit: 30,
	words: [
	{ id: "RAY-1", text: "Encontraría", category: WordClass.VERBO },
	{ id: "RAY-2", text: "a", category: WordClass.PREPOSICION },
	{ id: "RAY-3", text: "la", category: WordClass.DETERMINANTE },
	{ id: "RAY-4", text: "Maga", category: WordClass.SUSTANTIVO },
	{ id: "RAY-5", text: "o", category: WordClass.CONJUNCION },
	{ id: "RAY-6", text: "no", category: WordClass.ADVERBIO },
	{ id: "RAY-7", text: "la", category: WordClass.PRONOMBRE },
	{ id: "RAY-8", text: "encontraría", category: WordClass.VERBO },
	{ id: "RAY-9", text: "pero", category: WordClass.CONJUNCION },
	{ id: "RAY-10", text: "ya", category: WordClass.ADVERBIO },
	{ id: "RAY-11", text: "no", category: WordClass.ADVERBIO },
	{ id: "RAY-12", text: "la", category: WordClass.PRONOMBRE },
	{ id: "RAY-13", text: "buscaría.", category: WordClass.VERBO },
	]
	},
	{
	id: 223,
	title: "Don Quijote - Miguel de Cervantes",
	categoryGroup: 'Literatura universal',
	text: "En un lugar de la Mancha de cuyo nombre no quiero acordarme vivía un hidalgo.",
	targetCategory: WordClass.VERBO,
	timeLimit: 35,
	words: [
	{ id: "DQ-1", text: "En", category: WordClass.PREPOSICION },
	{ id: "DQ-2", text: "un", category: WordClass.DETERMINANTE },
	{ id: "DQ-3", text: "lugar", category: WordClass.SUSTANTIVO },
	{ id: "DQ-4", text: "de", category: WordClass.PREPOSICION },
	{ id: "DQ-5", text: "la", category: WordClass.DETERMINANTE },
	{ id: "DQ-6", text: "Mancha", category: WordClass.SUSTANTIVO },
	{ id: "DQ-7", text: "de", category: WordClass.PREPOSICION },
	{ id: "DQ-8", text: "cuyo", category: WordClass.DETERMINANTE },
	{ id: "DQ-9", text: "nombre", category: WordClass.SUSTANTIVO },
	{ id: "DQ-10", text: "no", category: WordClass.ADVERBIO },
	{ id: "DQ-11", text: "quiero", category: WordClass.VERBO },
	{ id: "DQ-12", text: "acordarme", category: WordClass.VERBO },
	{ id: "DQ-13", text: "vivía", category: WordClass.VERBO },
	{ id: "DQ-14", text: "un", category: WordClass.DETERMINANTE },
	{ id: "DQ-15", text: "hidalgo.", category: WordClass.SUSTANTIVO },
	]
	},
	{
	id: 224,
	title: "La divina comedia - Dante Alighieri",
	categoryGroup: 'Literatura universal',
	text: "A mitad del camino de la vida me encontré en una selva oscura.",
	targetCategory: WordClass.ADJETIVO,
	timeLimit: 30,
	words: [
	{ id: "DC-1", text: "A", category: WordClass.PREPOSICION },
	{ id: "DC-2", text: "mitad", category: WordClass.SUSTANTIVO },
	{ id: "DC-3", text: "del", category: WordClass.PREPOSICION },
	{ id: "DC-4", text: "camino", category: WordClass.SUSTANTIVO },
	{ id: "DC-5", text: "de", category: WordClass.PREPOSICION },
	{ id: "DC-6", text: "la", category: WordClass.DETERMINANTE },
	{ id: "DC-7", text: "vida", category: WordClass.SUSTANTIVO },
	{ id: "DC-8", text: "me", category: WordClass.PRONOMBRE },
	{ id: "DC-9", text: "encontré", category: WordClass.VERBO },
	{ id: "DC-10", text: "en", category: WordClass.PREPOSICION },
	{ id: "DC-11", text: "una", category: WordClass.DETERMINANTE },
	{ id: "DC-12", text: "selva", category: WordClass.SUSTANTIVO },
	{ id: "DC-13", text: "oscura.", category: WordClass.ADJETIVO },
	]
	},
	{
	id: 225,
	title: "El retrato de Dorian Gray - Oscar Wilde",
	categoryGroup: 'Literatura universal',
	text: "El estudio estaba lleno del rico aroma de las rosas y cuando la brisa agitaba los árboles entraba el pesado perfume de las lilas.",
	targetCategory: WordClass.ADJETIVO,
	timeLimit: 50,
	words: [
	{ id: "DG-1", text: "El", category: WordClass.DETERMINANTE },
	{ id: "DG-2", text: "estudio", category: WordClass.SUSTANTIVO },
	{ id: "DG-3", text: "estaba", category: WordClass.VERBO },
	{ id: "DG-4", text: "lleno", category: WordClass.ADJETIVO },
	{ id: "DG-5", text: "del", category: WordClass.PREPOSICION },
	{ id: "DG-6", text: "rico", category: WordClass.ADJETIVO },
	{ id: "DG-7", text: "aroma", category: WordClass.SUSTANTIVO },
	{ id: "DG-8", text: "de", category: WordClass.PREPOSICION },
	{ id: "DG-9", text: "las", category: WordClass.DETERMINANTE },
	{ id: "DG-10", text: "rosas", category: WordClass.SUSTANTIVO },
	{ id: "DG-11", text: "y", category: WordClass.CONJUNCION },
	{ id: "DG-12", text: "cuando", category: WordClass.CONJUNCION },
	{ id: "DG-13", text: "la", category: WordClass.DETERMINANTE },
	{ id: "DG-14", text: "brisa", category: WordClass.SUSTANTIVO },
	{ id: "DG-15", text: "agitaba", category: WordClass.VERBO },
	{ id: "DG-16", text: "los", category: WordClass.DETERMINANTE },
	{ id: "DG-17", text: "árboles", category: WordClass.SUSTANTIVO },
	{ id: "DG-18", text: "entraba", category: WordClass.VERBO },
	{ id: "DG-19", text: "el", category: WordClass.DETERMINANTE },
	{ id: "DG-20", text: "pesado", category: WordClass.ADJETIVO },
	{ id: "DG-21", text: "perfume", category: WordClass.SUSTANTIVO },
	{ id: "DG-22", text: "de", category: WordClass.PREPOSICION },
	{ id: "DG-23", text: "las", category: WordClass.DETERMINANTE },
	{ id: "DG-24", text: "lilas.", category: WordClass.SUSTANTIVO },
	]
	},
	{
	id: 226,
	title: "Beloved - Toni Morrison",
	categoryGroup: 'Literatura universal',
	text: "El ciento veinticuatro era malicioso lleno de rencor infantil.",
	targetCategory: WordClass.ADJETIVO,
	timeLimit: 25,
	words: [
	{ id: "BEL-1", text: "El", category: WordClass.DETERMINANTE },
	{ id: "BEL-2", text: "ciento", category: WordClass.DETERMINANTE },
	{ id: "BEL-3", text: "veinticuatro", category: WordClass.DETERMINANTE },
	{ id: "BEL-4", text: "era", category: WordClass.VERBO },
	{ id: "BEL-5", text: "malicioso", category: WordClass.ADJETIVO },
	{ id: "BEL-6", text: "lleno", category: WordClass.ADJETIVO },
	{ id: "BEL-7", text: "de", category: WordClass.PREPOSICION },
	{ id: "BEL-8", text: "rencor", category: WordClass.SUSTANTIVO },
	{ id: "BEL-9", text: "infantil.", category: WordClass.ADJETIVO },
	]
	},
	];


export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  { id: 'first_steps', title: '¡Primeros pasos!', description: 'Completa tu primer nivel con éxito.', icon: 'fa-shoe-prints', unlocked: false },
  { id: 'noun_expert', title: 'Experto en sustantivos', description: 'Identifica correctamente 100 sustantivos.', icon: 'fa-book', unlocked: false, progress: 0, goal: 100 },
  { id: 'speedster', title: 'Velocista de palabras', description: 'Completa un nivel con más del 50% del tiempo restante.', icon: 'fa-bolt', unlocked: false },
  { id: 'hidden_discoverer', title: 'Descubridor oculto', description: 'Encuentra el camino hacia el editor secreto.', icon: 'fa-user-secret', unlocked: false }
];

export const KONAMI_CODE = ['ArrowUp', 'ArrowUp', 'ArrowDown', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowLeft', 'ArrowRight', 'b', 'a'];
