
import { WordClass, Level, Achievement } from './types';

export const INITIAL_LEVELS: Level[] = [
  {
    id: 1,
    title: "El Bosque Mágico",
    text: "El gato negro corre rápido por el bosque verde y saltó sobre una rama pequeña.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 30,
    words: [
      { id: "1-1", text: "El", category: WordClass.DETERMINANTE },
      { id: "1-2", text: "gato", category: WordClass.SUSTANTIVO },
      { id: "1-3", text: "negro", category: WordClass.ADJETIVO },
      { id: "1-4", text: "corre", category: WordClass.VERBO },
      { id: "1-5", text: "rápido", category: WordClass.ADVERBIO },
      { id: "1-6", text: "por", category: WordClass.PREPOSICION },
      { id: "1-7", text: "el", category: WordClass.DETERMINANTE },
      { id: "1-8", text: "bosque", category: WordClass.SUSTANTIVO },
      { id: "1-9", text: "verde", category: WordClass.ADJETIVO },
      { id: "1-10", text: "y", category: WordClass.CONJUNCION },
      { id: "1-11", text: "saltó", category: WordClass.VERBO },
      { id: "1-12", text: "sobre", category: WordClass.PREPOSICION },
      { id: "1-13", text: "una", category: WordClass.DETERMINANTE },
      { id: "1-14", text: "rama", category: WordClass.SUSTANTIVO },
      { id: "1-15", text: "pequeña.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 2,
    title: "La Aventura Espacial",
    text: "Los astronautas valientes exploran planetas lejanos con sus naves plateadas.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 25,
    words: [
      { id: "2-1", text: "Los", category: WordClass.DETERMINANTE },
      { id: "2-2", text: "astronautas", category: WordClass.SUSTANTIVO },
      { id: "2-3", text: "valientes", category: WordClass.ADJETIVO },
      { id: "2-4", text: "exploran", category: WordClass.VERBO },
      { id: "2-5", text: "planetas", category: WordClass.SUSTANTIVO },
      { id: "2-6", text: "lejanos", category: WordClass.ADJETIVO },
      { id: "2-7", text: "con", category: WordClass.PREPOSICION },
      { id: "2-8", text: "sus", category: WordClass.DETERMINANTE },
      { id: "2-9", text: "naves", category: WordClass.SUSTANTIVO },
      { id: "2-10", text: "plateadas.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 3,
    title: "Receta de Cocina",
    text: "Nosotros cocinaremos hoy una tarta deliciosa porque tenemos mucha hambre.",
    targetCategory: WordClass.VERBO,
    timeLimit: 20,
    words: [
      { id: "3-1", text: "Nosotros", category: WordClass.PRONOMBRE },
      { id: "3-2", text: "cocinaremos", category: WordClass.VERBO },
      { id: "3-3", text: "hoy", category: WordClass.ADVERBIO },
      { id: "3-4", text: "una", category: WordClass.DETERMINANTE },
      { id: "3-5", text: "tarta", category: WordClass.SUSTANTIVO },
      { id: "3-6", text: "deliciosa", category: WordClass.ADJETIVO },
      { id: "3-7", text: "porque", category: WordClass.CONJUNCION },
      { id: "3-8", text: "tenemos", category: WordClass.VERBO },
      { id: "3-9", text: "mucha", category: WordClass.DETERMINANTE },
      { id: "3-10", text: "hambre.", category: WordClass.SUSTANTIVO },
    ]
  }
];

export const LITERARY_LEVELS: Level[] = [
  {
    id: 101,
    title: "La tía Tula - Unamuno",
    text: "Rosa se casó primero. Gertrudis, la hermana mayor, parecía resignada a quedarse para vestir imágenes, como decía la gente.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 30,
    words: [
      { id: "L1-1", text: "Rosa", category: WordClass.SUSTANTIVO },
      { id: "L1-2", text: "se", category: WordClass.PRONOMBRE },
      { id: "L1-3", text: "casó", category: WordClass.VERBO },
      { id: "L1-4", text: "primero.", category: WordClass.ADVERBIO },
      { id: "L1-5", text: "Gertrudis,", category: WordClass.SUSTANTIVO },
      { id: "L1-6", text: "la", category: WordClass.DETERMINANTE },
      { id: "L1-7", text: "hermana", category: WordClass.SUSTANTIVO },
      { id: "L1-8", text: "mayor,", category: WordClass.ADJETIVO },
      { id: "L1-9", text: "parecía", category: WordClass.VERBO },
      { id: "L1-10", text: "resignada", category: WordClass.ADJETIVO },
      { id: "L1-11", text: "a", category: WordClass.PREPOSICION },
      { id: "L1-12", text: "quedarse", category: WordClass.VERBO },
      { id: "L1-13", text: "para", category: WordClass.PREPOSICION },
      { id: "L1-14", text: "vestir", category: WordClass.VERBO },
      { id: "L1-15", text: "imágenes,", category: WordClass.SUSTANTIVO },
      { id: "L1-16", text: "como", category: WordClass.CONJUNCION },
      { id: "L1-17", text: "decía", category: WordClass.VERBO },
      { id: "L1-18", text: "la", category: WordClass.DETERMINANTE },
      { id: "L1-19", text: "gente.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 102,
    title: "El túnel - Sábato (Argentina)",
    text: "Bastará decir que soy Juan Pablo Castel, el pintor que mató a María Iribarne. Supongo que el proceso está en el recuerdo de todos.",
    targetCategory: WordClass.VERBO,
    timeLimit: 40,
    words: [
      { id: "L2-1", text: "Bastará", category: WordClass.VERBO },
      { id: "L2-2", text: "decir", category: WordClass.VERBO },
      { id: "L2-3", text: "que", category: WordClass.CONJUNCION },
      { id: "L2-4", text: "soy", category: WordClass.VERBO },
      { id: "L2-5", text: "Juan", category: WordClass.SUSTANTIVO },
      { id: "L2-6", text: "Pablo", category: WordClass.SUSTANTIVO },
      { id: "L2-7", text: "Castel,", category: WordClass.SUSTANTIVO },
      { id: "L2-8", text: "el", category: WordClass.DETERMINANTE },
      { id: "L2-9", text: "pintor", category: WordClass.SUSTANTIVO },
      { id: "L2-10", text: "que", category: WordClass.PRONOMBRE },
      { id: "L2-11", text: "mató", category: WordClass.VERBO },
      { id: "L2-12", text: "a", category: WordClass.PREPOSICION },
      { id: "L2-13", text: "María", category: WordClass.SUSTANTIVO },
      { id: "L2-14", text: "Iribarne.", category: WordClass.SUSTANTIVO },
      { id: "L2-15", text: "Supongo", category: WordClass.VERBO },
      { id: "L2-16", text: "que", category: WordClass.CONJUNCION },
      { id: "L2-17", text: "el", category: WordClass.DETERMINANTE },
      { id: "L2-18", text: "proceso", category: WordClass.SUSTANTIVO },
      { id: "L2-19", text: "está", category: WordClass.VERBO },
      { id: "L2-20", text: "en", category: WordClass.PREPOSICION },
      { id: "L2-21", text: "el", category: WordClass.DETERMINANTE },
      { id: "L2-22", text: "recuerdo", category: WordClass.SUSTANTIVO },
      { id: "L2-23", text: "de", category: WordClass.PREPOSICION },
      { id: "L2-24", text: "todos.", category: WordClass.PRONOMBRE },
    ]
  },
  {
    id: 103,
    title: "Pedro Páramo - Rulfo (México)",
    text: "Vine a Comala porque me dijeron que acá vivía mi padre, un tal Pedro Páramo. Mi madre me lo dijo.",
    targetCategory: WordClass.PRONOMBRE,
    timeLimit: 35,
    words: [
      { id: "L3-1", text: "Vine", category: WordClass.VERBO },
      { id: "L3-2", text: "a", category: WordClass.PREPOSICION },
      { id: "L3-3", text: "Comala", category: WordClass.SUSTANTIVO },
      { id: "L3-4", text: "porque", category: WordClass.CONJUNCION },
      { id: "L3-5", text: "me", category: WordClass.PRONOMBRE },
      { id: "L3-6", text: "dijeron", category: WordClass.VERBO },
      { id: "L3-7", text: "que", category: WordClass.CONJUNCION },
      { id: "L3-8", text: "acá", category: WordClass.ADVERBIO },
      { id: "L3-9", text: "vivía", category: WordClass.VERBO },
      { id: "L3-10", text: "mi", category: WordClass.DETERMINANTE },
      { id: "L3-11", text: "padre,", category: WordClass.SUSTANTIVO },
      { id: "L3-12", text: "un", category: WordClass.DETERMINANTE },
      { id: "L3-13", text: "tal", category: WordClass.DETERMINANTE },
      { id: "L3-14", text: "Pedro", category: WordClass.SUSTANTIVO },
      { id: "L3-15", text: "Páramo.", category: WordClass.SUSTANTIVO },
      { id: "L3-16", text: "Mi", category: WordClass.DETERMINANTE },
      { id: "L3-17", text: "madre", category: WordClass.SUSTANTIVO },
      { id: "L3-18", text: "me", category: WordClass.PRONOMBRE },
      { id: "L3-19", text: "lo", category: WordClass.PRONOMBRE },
      { id: "L3-20", text: "dijo.", category: WordClass.VERBO },
    ]
  },
  {
    id: 104,
    title: "Martín Fierro - Hernández (Argentina)",
    text: "Aquí me pongo a cantar al compás de la vigüela, que el hombre que lo desvela una pena extraordinaria.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 35,
    words: [
      { id: "L4-1", text: "Aquí", category: WordClass.ADVERBIO },
      { id: "L4-2", text: "me", category: WordClass.PRONOMBRE },
      { id: "L4-3", text: "pongo", category: WordClass.VERBO },
      { id: "L4-4", text: "a", category: WordClass.PREPOSICION },
      { id: "L4-5", text: "cantar", category: WordClass.VERBO },
      { id: "L4-6", text: "al", category: WordClass.PREPOSICION },
      { id: "L4-7", text: "compás", category: WordClass.SUSTANTIVO },
      { id: "L4-8", text: "de", category: WordClass.PREPOSICION },
      { id: "L4-9", text: "la", category: WordClass.DETERMINANTE },
      { id: "L4-10", text: "vigüela,", category: WordClass.SUSTANTIVO },
      { id: "L4-11", text: "que", category: WordClass.CONJUNCION },
      { id: "L4-12", text: "el", category: WordClass.DETERMINANTE },
      { id: "L4-13", text: "hombre", category: WordClass.SUSTANTIVO },
      { id: "L4-14", text: "que", category: WordClass.PRONOMBRE },
      { id: "L4-15", text: "lo", category: WordClass.PRONOMBRE },
      { id: "L4-16", text: "desvela", category: WordClass.VERBO },
      { id: "L4-17", text: "una", category: WordClass.DETERMINANTE },
      { id: "L4-18", text: "pena", category: WordClass.SUSTANTIVO },
      { id: "L4-19", text: "extraordinaria.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 105,
    title: "Doña Bárbara - Gallegos (Venezuela)",
    text: "Un bongo remonta el Arauca bordeando las barrancas de la margen derecha. La tripulación está formada por cuatro hombres.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 35,
    words: [
      { id: "L5-1", text: "Un", category: WordClass.DETERMINANTE },
      { id: "L5-2", text: "bongo", category: WordClass.SUSTANTIVO },
      { id: "L5-3", text: "remonta", category: WordClass.VERBO },
      { id: "L5-4", text: "el", category: WordClass.DETERMINANTE },
      { id: "L5-5", text: "Arauca", category: WordClass.SUSTANTIVO },
      { id: "L5-6", text: "bordeando", category: WordClass.VERBO },
      { id: "L5-7", text: "las", category: WordClass.DETERMINANTE },
      { id: "L5-8", text: "barrancas", category: WordClass.SUSTANTIVO },
      { id: "L5-9", text: "de", category: WordClass.PREPOSICION },
      { id: "L5-10", text: "la", category: WordClass.DETERMINANTE },
      { id: "L5-11", text: "margen", category: WordClass.SUSTANTIVO },
      { id: "L5-12", text: "derecha.", category: WordClass.ADJETIVO },
      { id: "L5-13", text: "La", category: WordClass.DETERMINANTE },
      { id: "L5-14", text: "tripulación", category: WordClass.SUSTANTIVO },
      { id: "L5-15", text: "está", category: WordClass.VERBO },
      { id: "L5-16", text: "formada", category: WordClass.ADJETIVO },
      { id: "L5-17", text: "por", category: WordClass.PREPOSICION },
      { id: "L5-18", text: "cuatro", category: WordClass.DETERMINANTE },
      { id: "L5-19", text: "hombres.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 106,
    title: "La vorágine - Rivera (Colombia)",
    text: "Antes que me hubiera apasionado por mujer alguna, jugué mi corazón al azar y me lo ganó la Violencia.",
    targetCategory: WordClass.PREPOSICION,
    timeLimit: 35,
    words: [
      { id: "L6-1", text: "Antes", category: WordClass.ADVERBIO },
      { id: "L6-2", text: "que", category: WordClass.CONJUNCION },
      { id: "L6-3", text: "me", category: WordClass.PRONOMBRE },
      { id: "L6-4", text: "hubiera", category: WordClass.VERBO },
      { id: "L6-5", text: "apasionado", category: WordClass.VERBO },
      { id: "L6-6", text: "por", category: WordClass.PREPOSICION },
      { id: "L6-7", text: "mujer", category: WordClass.SUSTANTIVO },
      { id: "L6-8", text: "alguna,", category: WordClass.DETERMINANTE },
      { id: "L6-9", text: "jugué", category: WordClass.VERBO },
      { id: "L6-10", text: "mi", category: WordClass.DETERMINANTE },
      { id: "L6-11", text: "corazón", category: WordClass.SUSTANTIVO },
      { id: "L6-12", text: "al", category: WordClass.PREPOSICION },
      { id: "L6-13", text: "azar", category: WordClass.SUSTANTIVO },
      { id: "L6-14", text: "y", category: WordClass.CONJUNCION },
      { id: "L6-15", text: "me", category: WordClass.PRONOMBRE },
      { id: "L6-16", text: "lo", category: WordClass.PRONOMBRE },
      { id: "L6-17", text: "ganó", category: WordClass.VERBO },
      { id: "L6-18", text: "la", category: WordClass.DETERMINANTE },
      { id: "L6-19", text: "Violencia.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 107,
    title: "Los de abajo - Azuela (México)",
    text: "A Demetrio Macías, la revolución lo había sacado de su rancho. Ahora regresaba como general victorioso.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 30,
    words: [
      { id: "L7-1", text: "A", category: WordClass.PREPOSICION },
      { id: "L7-2", text: "Demetrio", category: WordClass.SUSTANTIVO },
      { id: "L7-3", text: "Macías,", category: WordClass.SUSTANTIVO },
      { id: "L7-4", text: "la", category: WordClass.DETERMINANTE },
      { id: "L7-5", text: "revolución", category: WordClass.SUSTANTIVO },
      { id: "L7-6", text: "lo", category: WordClass.PRONOMBRE },
      { id: "L7-7", text: "había", category: WordClass.VERBO },
      { id: "L7-8", text: "sacado", category: WordClass.VERBO },
      { id: "L7-9", text: "de", category: WordClass.PREPOSICION },
      { id: "L7-10", text: "su", category: WordClass.DETERMINANTE },
      { id: "L7-11", text: "rancho.", category: WordClass.SUSTANTIVO },
      { id: "L7-12", text: "Ahora", category: WordClass.ADVERBIO },
      { id: "L7-13", text: "regresaba", category: WordClass.VERBO },
      { id: "L7-14", text: "como", category: WordClass.CONJUNCION },
      { id: "L7-15", text: "general", category: WordClass.SUSTANTIVO },
      { id: "L7-16", text: "victorioso.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 108,
    title: "El reino de este mundo - Carpentier (Cuba)",
    text: "Ti Noel observaba cómo las llamas lamían las vigas del techo. El incendio había comenzado en la cocina principal.",
    targetCategory: WordClass.VERBO,
    timeLimit: 35,
    words: [
      { id: "L8-1", text: "Ti", category: WordClass.SUSTANTIVO },
      { id: "L8-2", text: "Noel", category: WordClass.SUSTANTIVO },
      { id: "L8-3", text: "observaba", category: WordClass.VERBO },
      { id: "L8-4", text: "cómo", category: WordClass.ADVERBIO },
      { id: "L8-5", text: "las", category: WordClass.DETERMINANTE },
      { id: "L8-6", text: "llamas", category: WordClass.SUSTANTIVO },
      { id: "L8-7", text: "lamían", category: WordClass.VERBO },
      { id: "L8-8", text: "las", category: WordClass.DETERMINANTE },
      { id: "L8-9", text: "vigas", category: WordClass.SUSTANTIVO },
      { id: "L8-10", text: "del", category: WordClass.PREPOSICION },
      { id: "L8-11", text: "techo.", category: WordClass.SUSTANTIVO },
      { id: "L8-12", text: "El", category: WordClass.DETERMINANTE },
      { id: "L8-13", text: "incendio", category: WordClass.SUSTANTIVO },
      { id: "L8-14", text: "había", category: WordClass.VERBO },
      { id: "L8-15", text: "comenzado", category: WordClass.VERBO },
      { id: "L8-16", text: "en", category: WordClass.PREPOSICION },
      { id: "L8-17", text: "la", category: WordClass.DETERMINANTE },
      { id: "L8-18", text: "cocina", category: WordClass.SUSTANTIVO },
      { id: "L8-19", text: "principal.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 109,
    title: "La casa verde - Vargas Llosa (Perú)",
    text: "El sargento mira la oscura corriente del río. Los guardias están tendidos bajo el poncho, durmiendo.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 30,
    words: [
      { id: "L9-1", text: "El", category: WordClass.DETERMINANTE },
      { id: "L9-2", text: "sargento", category: WordClass.SUSTANTIVO },
      { id: "L9-3", text: "mira", category: WordClass.VERBO },
      { id: "L9-4", text: "la", category: WordClass.DETERMINANTE },
      { id: "L9-5", text: "oscura", category: WordClass.ADJETIVO },
      { id: "L9-6", text: "corriente", category: WordClass.SUSTANTIVO },
      { id: "L9-7", text: "del", category: WordClass.PREPOSICION },
      { id: "L9-8", text: "río.", category: WordClass.SUSTANTIVO },
      { id: "L9-9", text: "Los", category: WordClass.DETERMINANTE },
      { id: "L9-10", text: "guardias", category: WordClass.SUSTANTIVO },
      { id: "L9-11", text: "están", category: WordClass.VERBO },
      { id: "L9-12", text: "tendidos", category: WordClass.ADJETIVO },
      { id: "L9-13", text: "bajo", category: WordClass.PREPOSICION },
      { id: "L9-14", text: "el", category: WordClass.DETERMINANTE },
      { id: "L9-15", text: "poncho,", category: WordClass.SUSTANTIVO },
      { id: "L9-16", text: "durmiendo.", category: WordClass.VERBO },
    ]
  },
  {
    id: 110,
    title: "Rayuela - Cortázar (Argentina)",
    text: "Andábamos sin buscarnos pero sabiendo que andábamos para encontrarnos. Maga reía de mis explicaciones.",
    targetCategory: WordClass.PRONOMBRE,
    timeLimit: 30,
    words: [
      { id: "L10-1", text: "Andábamos", category: WordClass.VERBO },
      { id: "L10-2", text: "sin", category: WordClass.PREPOSICION },
      { id: "L10-3", text: "buscarnos", category: WordClass.VERBO },
      { id: "L10-4", text: "pero", category: WordClass.CONJUNCION },
      { id: "L10-5", text: "sabiendo", category: WordClass.VERBO },
      { id: "L10-6", text: "que", category: WordClass.CONJUNCION },
      { id: "L10-7", text: "andábamos", category: WordClass.VERBO },
      { id: "L10-8", text: "para", category: WordClass.PREPOSICION },
      { id: "L10-9", text: "encontrarnos.", category: WordClass.VERBO },
      { id: "L10-10", text: "Maga", category: WordClass.SUSTANTIVO },
      { id: "L10-11", text: "reía", category: WordClass.VERBO },
      { id: "L10-12", text: "de", category: WordClass.PREPOSICION },
      { id: "L10-13", text: "mis", category: WordClass.DETERMINANTE },
      { id: "L10-14", text: "explicaciones.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 111,
    title: "El Señor Presidente - Asturias (Guatemala)",
    text: "En ese instante se oyeron las campanadas. Nadie sabía de dónde venía aquel sonido metálico y persistente.",
    targetCategory: WordClass.ADVERBIO,
    timeLimit: 30,
    words: [
      { id: "L11-1", text: "En", category: WordClass.PREPOSICION },
      { id: "L11-2", text: "ese", category: WordClass.DETERMINANTE },
      { id: "L11-3", text: "instante", category: WordClass.SUSTANTIVO },
      { id: "L11-4", text: "se", category: WordClass.PRONOMBRE },
      { id: "L11-5", text: "oyeron", category: WordClass.VERBO },
      { id: "L11-6", text: "las", category: WordClass.DETERMINANTE },
      { id: "L11-7", text: "campanadas.", category: WordClass.SUSTANTIVO },
      { id: "L11-8", text: "Nadie", category: WordClass.PRONOMBRE },
      { id: "L11-9", text: "sabía", category: WordClass.VERBO },
      { id: "L11-10", text: "de", category: WordClass.PREPOSICION },
      { id: "L11-11", text: "dónde", category: WordClass.ADVERBIO },
      { id: "L11-12", text: "venía", category: WordClass.VERBO },
      { id: "L11-13", text: "aquel", category: WordClass.DETERMINANTE },
      { id: "L11-14", text: "sonido", category: WordClass.SUSTANTIVO },
      { id: "L11-15", text: "metálico", category: WordClass.ADJETIVO },
      { id: "L11-16", text: "y", category: WordClass.CONJUNCION },
      { id: "L11-17", text: "persistente.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 112,
    title: "Los pasos perdidos - Carpentier (Cuba)",
    text: "Hacía cuatro años y siete meses que no había vuelto a la ciudad donde transcurrió mi adolescencia.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 35,
    words: [
      { id: "L12-1", text: "Hacía", category: WordClass.VERBO },
      { id: "L12-2", text: "cuatro", category: WordClass.DETERMINANTE },
      { id: "L12-3", text: "años", category: WordClass.SUSTANTIVO },
      { id: "L12-4", text: "y", category: WordClass.CONJUNCION },
      { id: "L12-5", text: "siete", category: WordClass.DETERMINANTE },
      { id: "L12-6", text: "meses", category: WordClass.SUSTANTIVO },
      { id: "L12-7", text: "que", category: WordClass.CONJUNCION },
      { id: "L12-8", text: "no", category: WordClass.ADVERBIO },
      { id: "L12-9", text: "había", category: WordClass.VERBO },
      { id: "L12-10", text: "vuelto", category: WordClass.VERBO },
      { id: "L12-11", text: "a", category: WordClass.PREPOSICION },
      { id: "L12-12", text: "la", category: WordClass.DETERMINANTE },
      { id: "L12-13", text: "ciudad", category: WordClass.SUSTANTIVO },
      { id: "L12-14", text: "donde", category: WordClass.ADVERBIO },
      { id: "L12-15", text: "transcurrió", category: WordClass.VERBO },
      { id: "L12-16", text: "mi", category: WordClass.DETERMINANTE },
      { id: "L12-17", text: "adolescencia.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 113,
    title: "Sobre héroes y tumbas - Sábato (Argentina)",
    text: "Cuando volvió en sí se encontró rodeado de rostros ansiosos. Alguien le ofrecía un vaso de agua fría.",
    targetCategory: WordClass.PREPOSICION,
    timeLimit: 35,
    words: [
      { id: "L13-1", text: "Cuando", category: WordClass.CONJUNCION },
      { id: "L13-2", text: "volvió", category: WordClass.VERBO },
      { id: "L13-3", text: "en", category: WordClass.PREPOSICION },
      { id: "L13-4", text: "sí", category: WordClass.PRONOMBRE },
      { id: "L13-5", text: "se", category: WordClass.PRONOMBRE },
      { id: "L13-6", text: "encontró", category: WordClass.VERBO },
      { id: "L13-7", text: "rodeado", category: WordClass.ADJETIVO },
      { id: "L13-8", text: "de", category: WordClass.PREPOSICION },
      { id: "L13-9", text: "rostros", category: WordClass.SUSTANTIVO },
      { id: "L13-10", text: "ansiosos.", category: WordClass.ADJETIVO },
      { id: "L13-11", text: "Alguien", category: WordClass.PRONOMBRE },
      { id: "L13-12", text: "le", category: WordClass.PRONOMBRE },
      { id: "L13-13", text: "ofrecía", category: WordClass.VERBO },
      { id: "L13-14", text: "un", category: WordClass.DETERMINANTE },
      { id: "L13-15", text: "vaso", category: WordClass.SUSTANTIVO },
      { id: "L13-16", text: "de", category: WordClass.PREPOSICION },
      { id: "L13-17", text: "agua", category: WordClass.SUSTANTIVO },
      { id: "L13-18", text: "fría.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 114,
    title: "Huasipungo - Icaza (Ecuador)",
    text: "Los indios trabajaban desde el amanecer hasta el anochecer. Sus manos callosas sangraban entre las piedras ásperas del camino.",
    targetCategory: WordClass.VERBO,
    timeLimit: 40,
    words: [
      { id: "L14-1", text: "Los", category: WordClass.DETERMINANTE },
      { id: "L14-2", text: "indios", category: WordClass.SUSTANTIVO },
      { id: "L14-3", text: "trabajaban", category: WordClass.VERBO },
      { id: "L14-4", text: "desde", category: WordClass.PREPOSICION },
      { id: "L14-5", text: "el", category: WordClass.DETERMINANTE },
      { id: "L14-6", text: "amanecer", category: WordClass.SUSTANTIVO },
      { id: "L14-7", text: "hasta", category: WordClass.PREPOSICION },
      { id: "L14-8", text: "el", category: WordClass.DETERMINANTE },
      { id: "L14-9", text: "anochecer.", category: WordClass.SUSTANTIVO },
      { id: "L14-10", text: "Sus", category: WordClass.DETERMINANTE },
      { id: "L14-11", text: "manos", category: WordClass.SUSTANTIVO },
      { id: "L14-12", text: "callosas", category: WordClass.ADJETIVO },
      { id: "L14-13", text: "sangraban", category: WordClass.VERBO },
      { id: "L14-14", text: "entre", category: WordClass.PREPOSICION },
      { id: "L14-15", text: "las", category: WordClass.DETERMINANTE },
      { id: "L14-16", text: "piedras", category: WordClass.SUSTANTIVO },
      { id: "L14-17", text: "ásperas", category: WordClass.ADJETIVO },
      { id: "L14-18", text: "del", category: WordClass.PREPOSICION },
      { id: "L14-19", text: "camino.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 115,
    title: "Nada - Laforet (España)",
    text: "Por dificultades en el último momento para adquirir billetes, llegué a Barcelona a medianoche.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 35,
    words: [
      { id: "L15-1", text: "Por", category: WordClass.PREPOSICION },
      { id: "L15-2", text: "dificultades", category: WordClass.SUSTANTIVO },
      { id: "L15-3", text: "en", category: WordClass.PREPOSICION },
      { id: "L15-4", text: "el", category: WordClass.DETERMINANTE },
      { id: "L15-5", text: "último", category: WordClass.ADJETIVO },
      { id: "L15-6", text: "momento", category: WordClass.SUSTANTIVO },
      { id: "L15-7", text: "para", category: WordClass.PREPOSICION },
      { id: "L15-8", text: "adquirir", category: WordClass.VERBO },
      { id: "L15-9", text: "billetes,", category: WordClass.SUSTANTIVO },
      { id: "L15-10", text: "llegué", category: WordClass.VERBO },
      { id: "L15-11", text: "a", category: WordClass.PREPOSICION },
      { id: "L15-12", text: "Barcelona", category: WordClass.SUSTANTIVO },
      { id: "L15-13", text: "a", category: WordClass.PREPOSICION },
      { id: "L15-14", text: "medianoche.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 116,
    title: "El Aleph - Borges (Argentina)",
    text: "La candente mañana de febrero en que Beatriz Viterbo murió, después de una imperiosa agonia que no se rebajó un solo instante.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 40,
    words: [
      { id: "L16-1", text: "La", category: WordClass.DETERMINANTE },
      { id: "L16-2", text: "candente", category: WordClass.ADJETIVO },
      { id: "L16-3", text: "mañana", category: WordClass.SUSTANTIVO },
      { id: "L16-4", text: "de", category: WordClass.PREPOSICION },
      { id: "L16-5", text: "febrero", category: WordClass.SUSTANTIVO },
      { id: "L16-6", text: "en", category: WordClass.PREPOSICION },
      { id: "L16-7", text: "que", category: WordClass.CONJUNCION },
      { id: "L16-8", text: "Beatriz", category: WordClass.SUSTANTIVO },
      { id: "L16-9", text: "Viterbo", category: WordClass.SUSTANTIVO },
      { id: "L16-10", text: "murió,", category: WordClass.VERBO },
      { id: "L16-11", text: "después", category: WordClass.ADVERBIO },
      { id: "L16-12", text: "de", category: WordClass.PREPOSICION },
      { id: "L16-13", text: "una", category: WordClass.DETERMINANTE },
      { id: "L16-14", text: "imperiosa", category: WordClass.ADJETIVO },
      { id: "L16-15", text: "agonía", category: WordClass.SUSTANTIVO },
      { id: "L16-16", text: "que", category: WordClass.PRONOMBRE },
      { id: "L16-17", text: "no", category: WordClass.ADVERBIO },
      { id: "L16-18", text: "se", category: WordClass.PRONOMBRE },
      { id: "L16-19", text: "rebajó", category: WordClass.VERBO },
      { id: "L16-20", text: "un", category: WordClass.DETERMINANTE },
      { id: "L16-21", text: "solo", category: WordClass.ADJETIVO },
      { id: "L16-22", text: "instante.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 117,
    title: "Santa - Gamboa (México)",
    text: "Santa nació en el pueblecito de Chimalistac, allá por los rumbos de San Ángel. Era hija de labradores honrados.",
    targetCategory: WordClass.PREPOSICION,
    timeLimit: 35,
    words: [
      { id: "L17-1", text: "Santa", category: WordClass.SUSTANTIVO },
      { id: "L17-2", text: "nació", category: WordClass.VERBO },
      { id: "L17-3", text: "en", category: WordClass.PREPOSICION },
      { id: "L17-4", text: "el", category: WordClass.DETERMINANTE },
      { id: "L17-5", text: "pueblecito", category: WordClass.SUSTANTIVO },
      { id: "L17-6", text: "de", category: WordClass.PREPOSICION },
      { id: "L17-7", text: "Chimalistac,", category: WordClass.SUSTANTIVO },
      { id: "L17-8", text: "allá", category: WordClass.ADVERBIO },
      { id: "L17-9", text: "por", category: WordClass.PREPOSICION },
      { id: "L17-10", text: "los", category: WordClass.DETERMINANTE },
      { id: "L17-11", text: "rumbos", category: WordClass.SUSTANTIVO },
      { id: "L17-12", text: "de", category: WordClass.PREPOSICION },
      { id: "L17-13", text: "San", category: WordClass.SUSTANTIVO },
      { id: "L17-14", text: "Ángel.", category: WordClass.SUSTANTIVO },
      { id: "L17-15", text: "Era", category: WordClass.VERBO },
      { id: "L17-16", text: "hija", category: WordClass.SUSTANTIVO },
      { id: "L17-17", text: "de", category: WordClass.PREPOSICION },
      { id: "L17-18", text: "labradores", category: WordClass.SUSTANTIVO },
      { id: "L17-19", text: "honrados.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 118,
    title: "Conversación en La Catedral - Vargas Llosa (Perú)",
    text: "Desde la puerta de La Crónica Santiago mira la avenida Tacna sin amor. Los autos, los edificios desiguales y descoloridos.",
    targetCategory: WordClass.SUSTANTIVO,
    timeLimit: 40,
    words: [
      { id: "L18-1", text: "Desde", category: WordClass.PREPOSICION },
      { id: "L18-2", text: "la", category: WordClass.DETERMINANTE },
      { id: "L18-3", text: "puerta", category: WordClass.SUSTANTIVO },
      { id: "L18-4", text: "de", category: WordClass.PREPOSICION },
      { id: "L18-5", text: "La", category: WordClass.DETERMINANTE },
      { id: "L18-6", text: "Crónica", category: WordClass.SUSTANTIVO },
      { id: "L18-7", text: "Santiago", category: WordClass.SUSTANTIVO },
      { id: "L18-8", text: "mira", category: WordClass.VERBO },
      { id: "L18-9", text: "la", category: WordClass.DETERMINANTE },
      { id: "L18-10", text: "avenida", category: WordClass.SUSTANTIVO },
      { id: "L18-11", text: "Tacna", category: WordClass.SUSTANTIVO },
      { id: "L18-12", text: "sin", category: WordClass.PREPOSICION },
      { id: "L18-13", text: "amor.", category: WordClass.SUSTANTIVO },
      { id: "L18-14", text: "Los", category: WordClass.DETERMINANTE },
      { id: "L18-15", text: "autos,", category: WordClass.SUSTANTIVO },
      { id: "L18-16", text: "los", category: WordClass.DETERMINANTE },
      { id: "L18-17", text: "edificios", category: WordClass.SUSTANTIVO },
      { id: "L18-18", text: "desiguales", category: WordClass.ADJETIVO },
      { id: "L18-19", text: "y", category: WordClass.CONJUNCION },
      { id: "L18-20", text: "descoloridos.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 119,
    title: "Fervor de Buenos Aires - Borges (Argentina)",
    text: "Las calles de Buenos Aires ya son mi entraña. No las ávidas calles incómodas del trajín, sino las calles desganadas del barrio.",
    targetCategory: WordClass.VERBO,
    timeLimit: 40,
    words: [
      { id: "L19-1", text: "Las", category: WordClass.DETERMINANTE },
      { id: "L19-2", text: "calles", category: WordClass.SUSTANTIVO },
      { id: "L19-3", text: "de", category: WordClass.PREPOSICION },
      { id: "L19-4", text: "Buenos", category: WordClass.SUSTANTIVO },
      { id: "L19-5", text: "Aires", category: WordClass.SUSTANTIVO },
      { id: "L19-6", text: "ya", category: WordClass.ADVERBIO },
      { id: "L19-7", text: "son", category: WordClass.VERBO },
      { id: "L19-8", text: "mi", category: WordClass.DETERMINANTE },
      { id: "L19-9", text: "entraña.", category: WordClass.SUSTANTIVO },
      { id: "L19-10", text: "No", category: WordClass.ADVERBIO },
      { id: "L19-11", text: "las", category: WordClass.DETERMINANTE },
      { id: "L19-12", text: "ávidas", category: WordClass.ADJETIVO },
      { id: "L19-13", text: "calles", category: WordClass.SUSTANTIVO },
      { id: "L19-14", text: "incómodas", category: WordClass.ADJETIVO },
      { id: "L19-15", text: "del", category: WordClass.PREPOSICION },
      { id: "L19-16", text: "trajín,", category: WordClass.SUSTANTIVO },
      { id: "L19-17", text: "sino", category: WordClass.CONJUNCION },
      { id: "L19-18", text: "las", category: WordClass.DETERMINANTE },
      { id: "L19-19", text: "calles", category: WordClass.SUSTANTIVO },
      { id: "L19-20", text: "desganadas", category: WordClass.ADJETIVO },
      { id: "L19-21", text: "del", category: WordClass.PREPOSICION },
      { id: "L19-22", text: "barrio.", category: WordClass.SUSTANTIVO },
    ]
  },
  {
    id: 120,
    title: "El llano en llamas - Rulfo (México)",
    text: "Nos habían dado la tierra. Y nos la habían dado en aquel lugar donde ni los conejos corrían.",
    targetCategory: WordClass.CONJUNCION,
    timeLimit: 35,
    words: [
      { id: "L20-1", text: "Nos", category: WordClass.PRONOMBRE },
      { id: "L20-2", text: "habían", category: WordClass.VERBO },
      { id: "L20-3", text: "dado", category: WordClass.VERBO },
      { id: "L20-4", text: "la", category: WordClass.DETERMINANTE },
      { id: "L20-5", text: "tierra.", category: WordClass.SUSTANTIVO },
      { id: "L20-6", text: "Y", category: WordClass.CONJUNCION },
      { id: "L20-7", text: "nos", category: WordClass.PRONOMBRE },
      { id: "L20-8", text: "la", category: WordClass.PRONOMBRE },
      { id: "L20-9", text: "habían", category: WordClass.VERBO },
      { id: "L20-10", text: "dado", category: WordClass.VERBO },
      { id: "L20-11", text: "en", category: WordClass.PREPOSICION },
      { id: "L20-12", text: "aquel", category: WordClass.DETERMINANTE },
      { id: "L20-13", text: "lugar", category: WordClass.SUSTANTIVO },
      { id: "L20-14", text: "donde", category: WordClass.ADVERBIO },
      { id: "L20-15", text: "ni", category: WordClass.CONJUNCION },
      { id: "L20-16", text: "los", category: WordClass.DETERMINANTE },
      { id: "L20-17", text: "conejos", category: WordClass.SUSTANTIVO },
      { id: "L20-18", text: "corrían.", category: WordClass.VERBO },
    ]
  },
  {
    id: 121,
    title: "Canaima - Gallegos (Venezuela)",
    text: "Marcos Vargas llegó al caney cuando ya el sol estaba alto. Traía noticias de los hombres que trabajaban río arriba.",
    targetCategory: WordClass.ADVERBIO,
    timeLimit: 35,
    words: [
      { id: "L21-1", text: "Marcos", category: WordClass.SUSTANTIVO },
      { id: "L21-2", text: "Vargas", category: WordClass.SUSTANTIVO },
      { id: "L21-3", text: "llegó", category: WordClass.VERBO },
      { id: "L21-4", text: "al", category: WordClass.PREPOSICION },
      { id: "L21-5", text: "caney", category: WordClass.SUSTANTIVO },
      { id: "L21-6", text: "cuando", category: WordClass.CONJUNCION },
      { id: "L21-7", text: "ya", category: WordClass.ADVERBIO },
      { id: "L21-8", text: "el", category: WordClass.DETERMINANTE },
      { id: "L21-9", text: "sol", category: WordClass.SUSTANTIVO },
      { id: "L21-10", text: "estaba", category: WordClass.VERBO },
      { id: "L21-11", text: "alto.", category: WordClass.ADJETIVO },
      { id: "L21-12", text: "Traía", category: WordClass.VERBO },
      { id: "L21-13", text: "noticias", category: WordClass.SUSTANTIVO },
      { id: "L21-14", text: "de", category: WordClass.PREPOSICION },
      { id: "L21-15", text: "los", category: WordClass.DETERMINANTE },
      { id: "L21-16", text: "hombres", category: WordClass.SUSTANTIVO },
      { id: "L21-17", text: "que", category: WordClass.PRONOMBRE },
      { id: "L21-18", text: "trabajaban", category: WordClass.VERBO },
      { id: "L21-19", text: "río", category: WordClass.SUSTANTIVO },
      { id: "L21-20", text: "arriba.", category: WordClass.ADVERBIO },
    ]
  },
  {
    id: 122,
    title: "El mundo es ancho y ajeno - Alegría (Perú)",
    text: "La comunidad de Rumi tiene tierras desde hace tiempo inmemorial. Allí nacieron y murieron muchas generaciones de indios laboriosos.",
    targetCategory: WordClass.DETERMINANTE,
    timeLimit: 40,
    words: [
      { id: "L22-1", text: "La", category: WordClass.DETERMINANTE },
      { id: "L22-2", text: "comunidad", category: WordClass.SUSTANTIVO },
      { id: "L22-3", text: "de", category: WordClass.PREPOSICION },
      { id: "L22-4", text: "Rumi", category: WordClass.SUSTANTIVO },
      { id: "L22-5", text: "tiene", category: WordClass.VERBO },
      { id: "L22-6", text: "tierras", category: WordClass.SUSTANTIVO },
      { id: "L22-7", text: "desde", category: WordClass.PREPOSICION },
      { id: "L22-8", text: "hace", category: WordClass.VERBO },
      { id: "L22-9", text: "tiempo", category: WordClass.SUSTANTIVO },
      { id: "L22-10", text: "inmemorial.", category: WordClass.ADJETIVO },
      { id: "L22-11", text: "Allí", category: WordClass.ADVERBIO },
      { id: "L22-12", text: "nacieron", category: WordClass.VERBO },
      { id: "L22-13", text: "y", category: WordClass.CONJUNCION },
      { id: "L22-14", text: "murieron", category: WordClass.VERBO },
      { id: "L22-15", text: "muchas", category: WordClass.DETERMINANTE },
      { id: "L22-16", text: "generaciones", category: WordClass.SUSTANTIVO },
      { id: "L22-17", text: "de", category: WordClass.PREPOSICION },
      { id: "L22-18", text: "indios", category: WordClass.SUSTANTIVO },
      { id: "L22-19", text: "laboriosos.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 123,
    title: "Los ríos profundos - Arguedas (Perú)",
    text: "Infundía respeto, a pesar de su anticuada y sucia apariencia. Las personas principales del Cuzco lo saludaban seriamente.",
    targetCategory: WordClass.PRONOMBRE,
    timeLimit: 35,
    words: [
      { id: "L23-1", text: "Infundía", category: WordClass.VERBO },
      { id: "L23-2", text: "respeto,", category: WordClass.SUSTANTIVO },
      { id: "L23-3", text: "a", category: WordClass.PREPOSICION },
      { id: "L23-4", text: "pesar", category: WordClass.SUSTANTIVO },
      { id: "L23-5", text: "de", category: WordClass.PREPOSICION },
      { id: "L23-6", text: "su", category: WordClass.DETERMINANTE },
      { id: "L23-7", text: "anticuada", category: WordClass.ADJETIVO },
      { id: "L23-8", text: "y", category: WordClass.CONJUNCION },
      { id: "L23-9", text: "sucia", category: WordClass.ADJETIVO },
      { id: "L23-10", text: "apariencia.", category: WordClass.SUSTANTIVO },
      { id: "L23-11", text: "Las", category: WordClass.DETERMINANTE },
      { id: "L23-12", text: "personas", category: WordClass.SUSTANTIVO },
      { id: "L23-13", text: "principales", category: WordClass.ADJETIVO },
      { id: "L23-14", text: "del", category: WordClass.PREPOSICION },
      { id: "L23-15", text: "Cuzco", category: WordClass.SUSTANTIVO },
      { id: "L23-16", text: "lo", category: WordClass.PRONOMBRE },
      { id: "L23-17", text: "saludaban", category: WordClass.VERBO },
      { id: "L23-18", text: "seriamente.", category: WordClass.ADVERBIO },
    ]
  },
  {
    id: 124,
    title: "La colmena - Cela (España)",
    text: "Doña Rosa va y viene por entre las mesas del café, tropezando con los clientes que beben su chocolate espeso.",
    targetCategory: WordClass.ADJETIVO,
    timeLimit: 35,
    words: [
      { id: "L24-1", text: "Doña", category: WordClass.SUSTANTIVO },
      { id: "L24-2", text: "Rosa", category: WordClass.SUSTANTIVO },
      { id: "L24-3", text: "va", category: WordClass.VERBO },
      { id: "L24-4", text: "y", category: WordClass.CONJUNCION },
      { id: "L24-5", text: "viene", category: WordClass.VERBO },
      { id: "L24-6", text: "por", category: WordClass.PREPOSICION },
      { id: "L24-7", text: "entre", category: WordClass.PREPOSICION },
      { id: "L24-8", text: "las", category: WordClass.DETERMINANTE },
      { id: "L24-9", text: "mesas", category: WordClass.SUSTANTIVO },
      { id: "L24-10", text: "del", category: WordClass.PREPOSICION },
      { id: "L24-11", text: "café,", category: WordClass.SUSTANTIVO },
      { id: "L24-12", text: "tropezando", category: WordClass.VERBO },
      { id: "L24-13", text: "con", category: WordClass.PREPOSICION },
      { id: "L24-14", text: "los", category: WordClass.DETERMINANTE },
      { id: "L24-15", text: "clientes", category: WordClass.SUSTANTIVO },
      { id: "L24-16", text: "que", category: WordClass.PRONOMBRE },
      { id: "L24-17", text: "beben", category: WordClass.VERBO },
      { id: "L24-18", text: "su", category: WordClass.DETERMINANTE },
      { id: "L24-19", text: "chocolate", category: WordClass.SUSTANTIVO },
      { id: "L24-20", text: "espeso.", category: WordClass.ADJETIVO },
    ]
  },
  {
    id: 125,
    title: "Tiempo de silencio - Martín-Santos (España)",
    text: "Había una vez un rey que tenía tres hijas. Las tres eran hermosas pero la menor era la más bella de todas.",
    targetCategory: WordClass.VERBO,
    timeLimit: 40,
    words: [
      { id: "L25-1", text: "Había", category: WordClass.VERBO },
      { id: "L25-2", text: "una", category: WordClass.DETERMINANTE },
      { id: "L25-3", text: "vez", category: WordClass.SUSTANTIVO },
      { id: "L25-4", text: "un", category: WordClass.DETERMINANTE },
      { id: "L25-5", text: "rey", category: WordClass.SUSTANTIVO },
      { id: "L25-6", text: "que", category: WordClass.PRONOMBRE },
      { id: "L25-7", text: "tenía", category: WordClass.VERBO },
      { id: "L25-8", text: "tres", category: WordClass.DETERMINANTE },
      { id: "L25-9", text: "hijas.", category: WordClass.SUSTANTIVO },
      { id: "L25-10", text: "Las", category: WordClass.DETERMINANTE },
      { id: "L25-11", text: "tres", category: WordClass.DETERMINANTE },
      { id: "L25-12", text: "eran", category: WordClass.VERBO },
      { id: "L25-13", text: "hermosas", category: WordClass.ADJETIVO },
      { id: "L25-14", text: "pero", category: WordClass.CONJUNCION },
      { id: "L25-15", text: "la", category: WordClass.DETERMINANTE },
      { id: "L25-16", text: "menor", category: WordClass.ADJETIVO },
      { id: "L25-17", text: "era", category: WordClass.VERBO },
      { id: "L25-18", text: "la", category: WordClass.DETERMINANTE },
      { id: "L25-19", text: "más", category: WordClass.ADVERBIO },
      { id: "L25-20", text: "bella", category: WordClass.ADJETIVO },
      { id: "L25-21", text: "de", category: WordClass.PREPOSICION },
      { id: "L25-22", text: "todas.", category: WordClass.PRONOMBRE },
    ]
  }
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  { id: 'first_steps', title: '¡Primeros pasos!', description: 'Completa tu primer nivel con éxito.', icon: 'fa-shoe-prints', unlocked: false },
  { id: 'noun_expert', title: 'Experto en sustantivos', description: 'Identifica correctamente 100 sustantivos.', icon: 'fa-book', unlocked: false, progress: 0, goal: 100 },
  { id: 'speedster', title: 'Velocista de palabras', description: 'Completa un nivel con más del 50% del tiempo restante.', icon: 'fa-bolt', unlocked: false },
  { id: 'hidden_discoverer', title: 'Descubridor oculto', description: 'Encuentra el camino hacia el editor secreto.', icon: 'fa-user-secret', unlocked: false }
];

export const KONAMI_CODE = ['ArrowUp', 'ArrowUp', 'ArrowDown', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowLeft', 'ArrowRight', 'b', 'a'];